In [2]:
## For experiment with all the LLM I have pre processed and devided the dataset by taking a random 10%
## of the dataset. which will help i finetuning the model
## based on the output and result I will be taking the original dataset for further use

import pandas as pd
from pathlib import Path
import json

df = pd.read_parquet("/content/train-00000-of-00001.parquet")

In [3]:
df.head(5)

,question,answer,context,ticker,filing
0,What area did NVIDIA initially focus on before...,NVIDIA initially focused on PC graphics.,"Since our original focus on PC graphics, we ha...",NVDA,2023_10K
1,What are some of the recent applications of GP...,Recent applications of GPU-powered deep learni...,Some of the most recent applications of GPU-po...,NVDA,2023_10K
2,What significant invention did NVIDIA create i...,NVIDIA invented the GPU in 1999.,Our invention of the GPU in 1999 defined moder...,NVDA,2023_10K
3,How does NVIDIA's platform strategy contribute...,NVIDIA's platform strategy brings together har...,"NVIDIA has a platform strategy, bringing toget...",NVDA,2023_10K
4,What does NVIDIA's CUDA programming model enable?,NVIDIA's CUDA programming model opened the par...,With our introduction of the CUDA programming ...,NVDA,2023_10K

In [4]:
len(df.columns)

5

In [5]:
len(df)

7000

In [6]:
print(df.shape[0])

7000

In [7]:
print(df.shape[1])

5

In [8]:
## For finetuning I am slighlt changing the dataset. to save time and computaional resources I am using a random 10% of the dataset for improved efficiency
df_sample = df.sample(frac=0.1, random_state=42)

In [9]:
df_sample.shape

(700, 5)

In [11]:
df_sample.head(5
               )

,question,answer,context,ticker,filing
6500,What services does Iron Mountain provide to pr...,Iron Mountain provides services such as storin...,Iron Mountain helps organizations protect thei...,IRM,2023_10K
2944,How is inventory valued for financial reporting?,Inventory is valued at standard cost adjusted ...,"We value inventory at standard cost, adjusted ...",AMD,2023_10K
2024,Where can details about legal proceedings be f...,"Part II, Item 8, in the Notes to the Consolida...",Details about legal proceedings are included i...,GME,2023_10K
263,What financial model does the company use to e...,The company uses the Black-Scholes option-pric...,The fair value of stock option awards with onl...,TSLA,2023_10K
4350,What are the two reporting business segments o...,The two reporting business segments of the com...,Our operations are conducted in two reporting ...,DLTR,2023_10K

In [12]:
## saving only the required columsn for finetuning
data_ft = df_sample[['question','answer','context']].copy()

In [13]:
## Converting the dataframe to jsonl format
data_ft.to_json("updated_data.jsonl", orient="records", lines=True, force_ascii=False)