This is the notebook for experimention different chunking strategy and vector embedding to test RAG pipeline.

This notebook is reference from an online course on RAG implementation by VIZUARA: Vizuara is an AI training platform.

In [1]:
#!pip install PyMuPDF tqdm sentence-transformers accelerate bitsandbytes flash-attn --no-build-isolation

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
BASE_DIR = "/content/drive/MyDrive/10K_PDFs"

In [16]:
## To show the list of files

from pathlib import Path

p = Path(BASE_DIR)
pdf_files = sorted(p.glob("**/*.pdf"))
csv_files = sorted(p.glob("**/*.csv"))

print(f"PDFs: {len(pdf_files)} files")
print(f"CSVs: {len(csv_files)} files")

pdf_files[:5], csv_files[:5]

PDFs: 32 files
CSVs: 1 files

([PosixPath('/content/drive/MyDrive/10K_PDFs/3M_10K.pdf'),
  PosixPath('/content/drive/MyDrive/10K_PDFs/AIG_10K.pdf'),
  PosixPath('/content/drive/MyDrive/10K_PDFs/AT&T_10K.pdf'),
  PosixPath('/content/drive/MyDrive/10K_PDFs/Abbott_Laboratories_10K.pdf'),
  PosixPath('/content/drive/MyDrive/10K_PDFs/Alphabet_10K.pdf')],
 [PosixPath('/content/drive/MyDrive/10K_PDFs/yahoo_most_active_stocks.csv')])

In [5]:
import re
import fitz
import hashlib
from pathlib import Path
from typing import List, Dict

def text_processor(text: str) -> str:
    """
    Text pre processing and cleaning before storing it for chunking
    """
    if not text:
        return ""
    t = text.replace("\r\n", "\n").replace("\r", "\n")
    t = re.sub(r"(\w)-\s*\n\s*(\w)", r"\1\2", t)
    lines = [re.sub(r"[ \t]+", " ", ln.strip()) for ln in t.split("\n")]
    t = " ".join([ln for ln in lines if ln])
    t = re.sub(r"\s+", " ", t).strip()
    return t


def read_pdf(pdf_path: str) -> List[Dict]:
    """
    Read a PDF and return a list of page dicts ||||||| The list of all the dictionaries should be formatted as per below data
      doc_id,
      filename,
      page_no,
      char_count,
      word_count,
      sentence_count,
      page_token_count,
      text_clean
    """
    path = Path(pdf_path)
    if not path.exists():
        raise FileNotFoundError(f"PDF not found: {pdf_path}")

    st = path.stat()
    doc_id = hashlib.md5(f"{path.resolve()}|{st.st_size}|{int(st.st_mtime)}".encode("utf-8")).hexdigest()

    records: List[Dict] = []
    with fitz.open(str(path)) as doc:
        for i in range(len(doc)):
            page = doc.load_page(i)
            raw = page.get_text("text") or ""
            clean = text_processor(raw)

            words = clean.split()
            word_count = len(words)

            sentences = [s for s in re.split(r"(?<=[.!?])\s+", clean) if s.strip()] if clean else []
            sentence_count = len(sentences)

            records.append({
                "doc_id": doc_id,
                "filename": path.name,
                "page_no": i + 1,
                "char_count": len(clean),
                "word_count": word_count,
                "sentence_count": sentence_count,
                "page_token_count": word_count,
                "text_clean": clean,
            })
    return records

In [6]:
from pathlib import Path
from typing import List, Dict

def read_pdfs(pdf_paths: List[str]) -> List[Dict]:
    """
    This will process all my pdfs at a time
    This code is referenced from Gemini
    """
    all_records: List[Dict] = []
    for p in pdf_paths:
        try:
            all_records.extend(read_pdf(p))
        except Exception as e:
            print(f"[skip] {p}: {e}")
    return all_records


def read_pdfs_in_dir(folder: str, recursive: bool = True) -> List[Dict]:
    """
    extract all the pdf and merge in the list
    """
    base = Path(folder)
    if not base.exists():
        raise FileNotFoundError(f"Folder not found: {folder}")

    pdf_iter = base.rglob("*.pdf") if recursive else base.glob("*.pdf")
    pdf_paths = [str(p) for p in pdf_iter]

    # ignore CSVs or others file format
    pdf_paths = [p for p in pdf_paths if p.lower().endswith(".pdf")]

    return read_pdfs(pdf_paths)

In [19]:
# Process all the pdfs under this folder
all_pages = read_pdfs_in_dir("/content/drive/MyDrive/10K_PDFs", recursive=True)
# Corss check
len(all_pages), all_pages[100]

(3943,
 {'doc_id': '606f248247422e3fb28b2bab06659955',
  'filename': 'AIG_10K.pdf',
  'page_no': 41,
  'char_count': 490,
  'word_count': 77,
  'sentence_count': 4,
  'page_token_count': 77,
  'text_clean': 'Table of Contents SIGNATURES Pursuant to the requirements of the Securities Exchange Act of 1934, the registrant has duly caused this report to be signed on its behalf by the undersigned thereunto duly authorized. ALPHABET INC. Date: March 29, 2016 By: /s/ LARRY PAGE Larry Page Chief Executive Officer (Principal Executive Officer of Alphabet Inc.) GOOGLE INC. Date: March 29, 2016 By: /s/ SUNDAR PICHAI Sundar Pichai Chief Executive Officer (Principal Executive Officer of Google Inc.) 37'})

In [23]:
all_pages[35]

{'doc_id': 'c340c0cb912d4aad0efa9e652c9eeb63',
 'filename': 'apple_2024_10K.pdf',
 'page_no': 36,
 'char_count': 2228,
 'word_count': 305,
 'sentence_count': 4,
 'page_token_count': 305,
 'text_clean': 'Apple Inc. CONSOLIDATED STATEMENTS OF CASH FLOWS (In millions) Years ended September 28, 2024 September 30, 2023 September 24, 2022 Cash, cash equivalents, and restricted cash and cash equivalents, beginning balances $ 30,737 $ 24,977 $ 35,929 Operating activities: Net income 93,736 96,995 99,803 Adjustments to reconcile net income to cash generated by operating activities: Depreciation and amortization 11,445 11,519 11,104 Share-based compensation expense 11,688 10,833 9,038 Other (2,266) (2,227) 1,006 Changes in operating assets and liabilities: Accounts receivable, net (3,788) (1,688) (1,823) Vendor non-trade receivables (1,356) 1,271 (7,520) Inventories (1,046) (1,618) 1,484 Other current and non-current assets (11,731) (5,684) (6,499) Accounts payable 6,020 (1,889) 9,448 Other current and non-current liabilities 15,552 3,031 6,110 Cash generated by operating activities 118,254 110,543 122,151 Investing activities: Purchases of marketable securities (48,656) (29,513) (76,923) Proceeds from maturities of marketable securities 51,211 39,686 29,917 Proceeds from sales of marketable securities 11,135 5,828 37,446 Payments for acquisition of property, plant and equipment (9,447) (10,959) (10,708) Other (1,308) (1,337) (2,086) Cash generated by/(used in) investing activities 2,935 3,705 (22,354) Financing activities: Payments for taxes related to net share settlement of equity awards (5,441) (5,431) (6,223) Payments for dividends and dividend equivalents (15,234) (15,025) (14,841) Repurchases of common stock (94,949) (77,550) (89,402) Proceeds from issuance of term debt, net — 5,228 5,465 Repayments of term debt (9,958) (11,151) (9,543) Proceeds from/(Repayments of) commercial paper, net 3,960 (3,978) 3,955 Other (361) (581) (160) Cash used in financing activities (121,983) (108,488) (110,749) Increase/(Decrease) in cash, cash equivalents, and restricted cash and cash equivalents (794) 5,760 (10,952) Cash, cash equivalents, and restricted cash and cash equivalents, ending balances $ 29,943 $ 30,737 $ 24,977 Supplemental cash flow disclosure: Cash paid for income taxes, net $ 26,102 $ 18,679 $ 19,573 See accompanying Notes to Consolidated Financial Statements. Apple Inc. | 2024 Form 10-K | 33'}

In [27]:
all_pages[167]['text_clean']

"Redeemable Noncontrolling Interest Noncontrolling interests that are redeemable outside the Company's control at fixed or determinable prices and dates are presented as temporary equity in the Consolidated Balance Sheets. Redeemable noncontrolling interests are recorded at the greater of the redemption fair value or the carrying value of the noncontrolling interest and adjusted each reporting period for income, loss and any distributions made. Remeasurements to the redemption value of the redeemable noncontrolling interest are recognized in capital in excess of par. The Company has a redeemable noncontrolling interest related to an acquisition in the Walmart U.S. segment as the minority interest owner holds a put option which may require the Company to purchase its interest beginning in December 2027, with annual options thereafter. Revenue Recognition Net Sales The Company recognizes sales revenue, net of sales taxes and estimated sales returns, at the time it sells merchandise or provides services to the customer. eCommerce sales include shipping revenue and are recorded upon delivery to the customer. Estimated sales returns are calculated based on expected returns. Financial, Advertising and Other Services The Company recognizes revenue from service transactions at the time the service is performed. Generally, revenue from services is classified as a component of net sales in the Company's Consolidated Statements of Income. Membership and Other Income Membership and other income primarily includes membership fee revenue associated with the Company's various membership offerings for customers and members across each reportable segment. Membership fee revenue is recognized over the term of the membership, which is typically 12 months. Membership fee revenue was $3.8 billion for fiscal 2025, $3.1 billion for fiscal 2024 and $2.6 billion for fiscal 2023. Deferred membership fee revenue is included in accrued liabilities in the Company's Consolidated Balance Sheets. Additionally, membership and other income includes items such as rental and tenant income, recycling income and gift card breakage income. Gift Cards Customer purchases of gift cards are not recognized as sales until the card is redeemed and the customer purchases merchandise using the gift card, thus a liability for deferred gift card revenue is recorded within accrued liabilities in the Consolidated Balance Sheets. Refer to Note 5. Gift cards in the U.S. and some countries do not carry an expiration date; therefore, customers and members can redeem their gift cards for merchandise and services indefinitely. Gift cards in some countries where the Company does business have expiration dates. While gift cards are generally redeemed within 12 months, a certain number of gift cards, both with and without expiration dates, will not be fully redeemed. Management estimates unredeemed balances and recognizes gift card breakage income for these amounts in membership and other income in the Company's Consolidated Statements of Income over the expected redemption period. Cost of Sales Cost of sales includes costs of merchandise sold and services performed; costs of transporting merchandise to the Company's distribution facilities, stores, clubs, and customers; and also includes warehousing costs for the Sam's Club U.S. segment and import distribution centers. Cost of sales is reduced by supplier payments, except in certain situations as described below. Payments from Suppliers The Company receives consideration from suppliers for various programs, primarily volume incentives, warehouse allowances and reimbursements for specific programs such as markdowns, margin protection, certain advertising arrangements and supplierspecific fixtures. Payments from suppliers are accounted for as a reduction of cost of sales and recognized in the Company's Consolidated Statements of Income when the related inventory is sold, except in situations when the payment is in exchange for a distinct good or service or a reimbursement of specific, incremental and identifiable costs. 63"

In [17]:
import os, pandas as pd
from google.colab import drive
drive.mount('/content/drive')

out_dir = "/content/drive/MyDrive/10k_processed"
os.makedirs(out_dir, exist_ok=True)

df = pd.DataFrame(all_pages)
df.to_parquet(f"{out_dir}/pages.parquet", engine="pyarrow", compression="zstd", index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
import pandas as pd

# for understanding our data
df = pd.DataFrame(all_pages)

df.head(5)

,doc_id,filename,page_no,char_count,word_count,sentence_count,page_token_count,text_clean
0,c340c0cb912d4aad0efa9e652c9eeb63,apple_2024_10K.pdf,1,2063,354,8,354,UNITED STATES SECURITIES AND EXCHANGE COMMISSI...
1,c340c0cb912d4aad0efa9e652c9eeb63,apple_2024_10K.pdf,2,3123,481,16,481,Indicate by check mark whether the Registrant ...
2,c340c0cb912d4aad0efa9e652c9eeb63,apple_2024_10K.pdf,3,1350,208,25,208,Apple Inc. Form 10-K For the Fiscal Year Ended...
3,c340c0cb912d4aad0efa9e652c9eeb63,apple_2024_10K.pdf,4,3628,575,26,575,This Annual Report on Form 10-K (“Form 10-K”) ...
4,c340c0cb912d4aad0efa9e652c9eeb63,apple_2024_10K.pdf,5,3648,530,22,530,Services Advertising The Company’s advertising...

In [15]:
df.describe()

           page_no   char_count   word_count  sentence_count  page_token_count
count  3943.000000  3943.000000  3943.000000     3943.000000       3943.000000
mean     97.208978  3415.208978   517.459802       17.947248        517.459802
std     107.557748  1916.907913   283.012394       12.331966        283.012394
min       1.000000     0.000000     0.000000        0.000000          0.000000
25%      32.000000  2017.000000   315.000000        8.000000        315.000000
50%      68.000000  3526.000000   541.000000       18.000000        541.000000
75%     112.000000  4898.000000   734.000000       27.000000        734.000000
max     569.000000  9150.000000  1362.000000       78.000000       1362.000000

## Chunking

In [30]:
## First we will clean the pages where total word is less than 50
from typing import List, Dict, Tuple

def drop_junk_pages(records: List[Dict], min_words: int = 50) -> Tuple[List[Dict], List[Dict]]:
    """
    Keep pages with word_count >= min_words
    This is to exclude unncessary information from our dataset
    """
    get_wc = lambda r: int(r.get("word_count") or 0)
    kept   = [r for r in records if get_wc(r) >= min_words]
    junk   = [r for r in records if get_wc(r) <  min_words]
    return kept, junk



kept_pages, junk_pages = drop_junk_pages(all_pages, min_words=50)
len(kept_pages), len(junk_pages)

(3603, 340)

In [31]:
import re
from typing import List, Dict
## -------------------------------------------------
## sfixed size splitter
## Splitting 10 sentences with 2 overlap sentences
## This code is referencced from cahtgpt
## -------------------------------------------------
SENT_SPLIT = re.compile(r"(?<=[.!?])\s+")

def split_sentences_with_pages(pages: List[Dict]) -> List[tuple]:
    """pages: list of page dicts for one doc (sorted by page_no).
       returns [(sentence, page_no), ...]"""
    out = []
    for p in pages:
        txt = (p.get("text_clean") or "").strip()
        if not txt:
            continue
        parts = [s.strip() for s in SENT_SPLIT.split(txt) if s.strip()]
        out.extend((s, int(p["page_no"])) for s in parts)
    return out

def chunk_by_sentences(
    records: List[Dict],
    sentences_per_chunk: int = 10,
    overlap: int = 2
) -> List[Dict]:
    """Fixed-size sentence chunking per document (doc_id)."""
    assert sentences_per_chunk > 0 and 0 <= overlap < sentences_per_chunk
    step = sentences_per_chunk - overlap

    # Specific to individual documents
    by_doc: Dict[str, List[Dict]] = {}
    for r in records:
        by_doc.setdefault(r["doc_id"], []).append(r)

    chunks: List[Dict] = []

    for doc_id, pages in by_doc.items():
        pages = sorted(pages, key=lambda r: int(r["page_no"]))
        filename = pages[0]["filename"] if pages else "unknown.pdf"

        sent_with_pages = split_sentences_with_pages(pages)
        n = len(sent_with_pages)
        if n == 0:
            continue

        chunk_id = 1
        i = 0
        while i < n:
            j = min(i + sentences_per_chunk, n)
            sentences = [s for s, _pg in sent_with_pages[i:j]]
            src_pages = [pg for _s, pg in sent_with_pages[i:j]]

            text = " ".join(sentences).strip()
            words = text.split()
            chunk = {
                "doc_id": doc_id,
                "filename": filename,
                "chunk_id": chunk_id,
                "page_start": min(src_pages),
                "page_end": max(src_pages),
                "source_pages": sorted(set(src_pages)),
                "sentence_count": len(sentences),
                "word_count": len(words),
                "char_count": len(text),
                "page_token_count": len(words),
                "text_clean": text,
            }
            chunks.append(chunk)

            chunk_id += 1
            if j == n:
                break
            i += step


    chunks.sort(key=lambda r: (r["filename"], r["chunk_id"]))
    return chunks

In [32]:
## initialising the chunking based on 10 snetence and 2 overlap sentence
chunks = chunk_by_sentences(kept_pages, sentences_per_chunk=10, overlap=2)
len(chunks), chunks[0]

(8817,
 {'doc_id': '9cf140658edcf90c20d3825c90fd9c0f',
  'filename': '3M_10K.pdf',
  'chunk_id': 1,
  'page_start': 1,
  'page_end': 1,
  'source_pages': [1],
  'sentence_count': 10,
  'word_count': 348,
  'char_count': 2076,
  'page_token_count': 348,
  'text_clean': 'Table of Contents UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington, D.C. 20549 FORM 10-K ☒ ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 For the fiscal year ended December 31, 2024 or o TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 For the transition period from __________ to __________ Commission file number 1-3285 3M COMPANY State of Incorporation: Delaware I.R.S. Employer Identification No. 41-0417775 Principal executive offices: 3M Center, St. Paul, Minnesota 55144 Telephone number: (651) 733-1110 Securities registered pursuant to Section 12(b) of the Act: Title of each class Trading Symbol(s) Name of each exchange on which registered Common Stock, Par Value $.01 Per Share MMM New York Stock Exchange MMM Chicago Stock Exchange, Inc. 1.500% Notes due 2026 MMM26 New York Stock Exchange 1.750% Notes due 2030 MMM30 New York Stock Exchange 1.500% Notes due 2031 MMM31 New York Stock Exchange Note: The common stock of the registrant is also traded on the SIX Swiss Exchange. Securities registered pursuant to section 12(g) of the Act: None Indicate by check mark if the registrant is a well-known seasoned issuer, as defined in Rule 405 of the Securities Act. Yes x No o Indicate by check mark if the registrant is not required to file reports pursuant to Section 13 or Section 15(d) of the Act. Yes o No x Indicate by check mark whether the registrant (1) has filed all reports required to be filed by Section 13 or 15(d) of the Securities Exchange Act of 1934 during the preceding 12 months (or for such shorter period that the registrant was required to file such reports), and (2) has been subject to such filing requirements for the past 90 days. Yes x No o Indicate by check mark whether the registrant has submitted electronically every Interactive Data File required to be submitted pursuant to Rule 405 of Regulation S-T (§ 232.405 of this chapter) during the preceding 12 months (or for such shorter period that the registrant was required to submit such files).'})

In [45]:
len(chunks), chunks[346]

(8817,
 {'doc_id': '606f248247422e3fb28b2bab06659955',
  'filename': 'AIG_10K.pdf',
  'chunk_id': 14,
  'page_start': 6,
  'page_end': 6,
  'source_pages': [6],
  'sentence_count': 10,
  'word_count': 289,
  'char_count': 1848,
  'page_token_count': 289,
  'text_clean': 'John holds a Master of Business Administration degree from Harvard Business School, and a Master of Science degree in electrical engineering and computer science, and a Bachelor of Science degree in electrical engineering from Rice University. Diane B. Greene has served as a member of our Board of Directors since January 2012 and as a Senior Vice President of Google since December 2015. Diane has also been a member of the board of directors of Intuit Inc., a provider of business and financial management solutions, since August 2006 and serves on its audit and risk committee and nominating and corporate governance committee. Diane co-founded VMware, Inc., a virtualization software company, in 1998 and took the company public in 2007. She served as Chief Executive Officer and President of VMware from 1998 to 2008, as a member of the board of directors of VMware from 2007 to 2008, and as an Executive Vice President of EMC Corporation, a provider of information infrastructure and virtual infrastructure technologies, solutions and services, from 2005 to 2008. Prior to VMware, Diane held technical leadership positions at Silicon Graphics Inc., a provider of technical computing, storage and data center solutions, Tandem Computers, Inc., a manufacturer of computer systems, and Sybase Inc., an enterprise software and services company, and was Chief Executive Officer of VXtreme, Inc., a developer of streaming media solutions. Diane is also a member of The MIT Corporation, the governing body of the Massachusetts Institute of Technology. Diane holds a Master of Science degree in computer science from the University of California, Berkeley, a Master of Science degree in naval architecture from the Massachusetts Institute of Technology, and a Bachelor of Arts degree in mechanical engineering from the University of Vermont. John L.'})

In [46]:
len(chunks), chunks[347]

(8817,
 {'doc_id': '606f248247422e3fb28b2bab06659955',
  'filename': 'AIG_10K.pdf',
  'chunk_id': 15,
  'page_start': 6,
  'page_end': 6,
  'source_pages': [6],
  'sentence_count': 10,
  'word_count': 226,
  'char_count': 1398,
  'page_token_count': 226,
  'text_clean': 'Diane holds a Master of Science degree in computer science from the University of California, Berkeley, a Master of Science degree in naval architecture from the Massachusetts Institute of Technology, and a Bachelor of Arts degree in mechanical engineering from the University of Vermont. John L. Hennessy has served as a member of our Board of Directors since April 2004, and as Lead Independent Director since April 2007. John has served as the President of Stanford University since September 2000. John has also been a member of the board of directors of Cisco Systems, Inc., a networking equipment company, since January 2002, and serves on its nominating and governance committee and acquisition committee. He also serves as a trustee of the Gordon and Betty Moore Foundation. From 1994 to August 2000, John held various positions at Stanford, including Dean of the Stanford University School of Engineering and Chair of the Stanford University Department of Computer Science. John holds a Doctoral degree and a Master of Science degree in computer science from the State University of New York, Stony Brook, and a Bachelor of Science degree in electrical engineering from Villanova University. John has announced that he plans to resign from his position as the President of Stanford University in August 2016. Ann Mather has served as a member of our Board of Directors since November 2005.'})

In [47]:
len(chunks), chunks[348]

(8817,
 {'doc_id': '606f248247422e3fb28b2bab06659955',
  'filename': 'AIG_10K.pdf',
  'chunk_id': 16,
  'page_start': 6,
  'page_end': 6,
  'source_pages': [6],
  'sentence_count': 10,
  'word_count': 250,
  'char_count': 1514,
  'page_token_count': 250,
  'text_clean': 'John has announced that he plans to resign from his position as the President of Stanford University in August 2016. Ann Mather has served as a member of our Board of Directors since November 2005. Ann has also been a member of the board of directors of: Arista Networks, Inc., a computer networking company, since June 2013, and serves as chair of its audit committee; Glu Mobile Inc., a publisher of mobile games, since September 2005, and serves on its nominating and corporate governance committee; Netflix, Inc., a streaming media company, since July 2010, and serves as chair of its audit committee; and Shutterfly, Inc., an internet-based image publishing company, since May 2013 and serves on its audit committee. Ann has also been an independent trustee to the Dodge & Cox Funds board of trustees since May 2011. Ann was previously a director of MoneyGram International, Inc., a global payment services company, from May 2010 to May 2013, and Solazyme, Inc., a biotechnology company, from April 2011 to November 2014. From 1999 to 2004, Ann was Executive Vice President and Chief Financial Officer of Pixar, a computer animation film studio. Prior to her service at Pixar, Ann was Executive Vice President and Chief Financial Officer of Village Roadshow Pictures, the film production division of Village Roadshow Limited. Ann holds a Master of Arts degree from Cambridge University in England and is a chartered accountant. Alan R. Mulally has served as a member of our Board of Directors since July 2014.'})

In [48]:
len(chunks), chunks[349]

(8817,
 {'doc_id': '606f248247422e3fb28b2bab06659955',
  'filename': 'AIG_10K.pdf',
  'chunk_id': 17,
  'page_start': 6,
  'page_end': 6,
  'source_pages': [6],
  'sentence_count': 10,
  'word_count': 158,
  'char_count': 958,
  'page_token_count': 158,
  'text_clean': 'Alan R. Mulally has served as a member of our Board of Directors since July 2014. Alan served as President and Chief Executive Officer of Ford Motor Company, a global automotive company, from September 2006 through June 2014. Alan was previously a member of the board of directors of Ford and served on its finance committee from September 2006 through June 2014. From March 2001 to September 2006, Alan served as Executive Vice President of the Boeing Company and President and Chief Executive Officer of Boeing Commercial Airplanes, Inc. He also was a member of the Boeing Executive Council. Prior to that time, he served as President of Boeing’s space and defense business. Alan served as co-chair of the Washington Competitiveness Council and sat on the advisory boards of NASA, the University of Washington, the University of Kansas, the Massachusetts Institute of Technology, and the U.S. Air Force Scientific Advisory Board. He is a member of the U.S.'})

Embedding using sentence-transformers/all-mpnet-base-v2

In [51]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(model_name_or_path="sentence-transformers/all-mpnet-base-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [52]:
sentences = [
    """Alan R. Mulally has served as a member of our Board of Directors since July 2014.
    Alan served as President and Chief Executive Officer of Ford Motor Company, a global automotive company,
    from September 2006 through June 2014. Alan was previously a member of the board of directors of Ford and served on its finance committee
    from September 2006 through June 2014. From March 2001 to September 2006, Alan served as Executive Vice President of the Boeing Company
    and President and Chief Executive Officer of Boeing Commercial Airplanes, Inc. He also was a member of the Boeing Executive Council.
    Prior to that time, he served as President of Boeing’s space and defense business.
    Alan served as co-chair of the Washington Competitiveness Council and sat on the advisory boards of NASA,
    the University of Washington, the University of Kansas, the Massachusetts Institute of Technology,
    and the U.S. Air Force Scientific Advisory Board. He is a member of the U.S.
    """
]

In [53]:
embeddings = embedding_model.encode(sentences)
embedding_dict = dict(zip(sentences, embeddings))

for sentence, embedding in embedding_dict.items():
  print("Sentence :", sentence)
  print("Embedding :", embedding)
  print("")

Sentence : Alan R. Mulally has served as a member of our Board of Directors since July 2014.
    Alan served as President and Chief Executive Officer of Ford Motor Company, a global automotive company,
    from September 2006 through June 2014. Alan was previously a member of the board of directors of Ford and served on its finance committee
    from September 2006 through June 2014. From March 2001 to September 2006, Alan served as Executive Vice President of the Boeing Company
    and President and Chief Executive Officer of Boeing Commercial Airplanes, Inc. He also was a member of the Boeing Executive Council.
    Prior to that time, he served as President of Boeing’s space and defense business.
    Alan served as co-chair of the Washington Competitiveness Council and sat on the advisory boards of NASA,
    the University of Washington, the University of Kansas, the Massachusetts Institute of Technology,
    and the U.S. Air Force Scientific Advisory Board. He is a member of the U.S.

Embedding : [ 1.52979502e-02  8.16121325e-02 -1.01758139e-02  3.94122005e-02
  2.18595508e-02 -3.55717205e-02  2.07800567e-02 -1.35786040e-02
 -1.36985183e-02 -3.07068173e-02 -3.73442448e-03  4.92928922e-02
  2.34565083e-02  2.61232108e-02  1.44060911e-03  2.71640625e-02
  2.28328295e-02 -5.48845604e-02  7.15385452e-02  2.30422127e-03
 -4.00384404e-02  7.62421452e-03 -3.10727842e-02 -2.30713980e-03
 -2.35793069e-02 -1.62423179e-02  4.72124070e-02  2.56145168e-02
  3.33646946e-02  3.08128409e-02 -1.67955253e-02 -1.74932200e-02
 -1.11423880e-02 -6.29994869e-02  2.49463437e-06 -7.35627301e-03
  6.27347268e-03 -2.23105606e-02  4.43115756e-02  2.39616465e-02
  3.52915772e-03  7.64679089e-02 -4.31611128e-02  5.94715364e-02
 -2.38730032e-02  5.09637967e-02 -4.15335037e-02 -2.23991927e-02
 -3.83496135e-02  8.90880998e-04  1.19843306e-02  3.18764523e-02
 -1.03213014e-02  1.97118875e-02  1.22854505e-02 -2.10550552e-05
  2.00014561e-03 -2.04229122e-03 -2.62668878e-02 -6.92225322e-02
 -1.82738993e-02  8.28366205e-02  8.08991864e-03 -3.78712192e-02
  3.31477821e-02  6.86233193e-02  3.76200788e-02  9.77124320e-04
  2.17130110e-02  5.65845333e-03  7.06347451e-02 -1.35957757e-02
  2.45424565e-02  3.30795608e-02  5.59522398e-02 -1.72500033e-02
  4.19544689e-02  2.08701808e-02 -2.94588935e-02 -1.25622256e-02
  1.37430374e-02  1.55879874e-02 -2.62081195e-02  3.91899534e-02
 -2.78183576e-02  1.72680337e-02 -3.43143791e-02 -4.17099893e-02
  1.10653844e-02 -1.44930249e-02  4.63634692e-02 -1.05648367e-02
  4.65833815e-03 -2.33974084e-02  1.40972100e-02 -7.77703896e-03
 -9.90633201e-03  4.90680933e-02 -4.57765609e-02 -8.59725475e-02
 -3.95871289e-02  8.13242700e-03  3.25398445e-02  3.07229236e-02
 -5.71308583e-02  6.98678643e-02  2.08549947e-02  5.67006296e-04
 -3.26221809e-02  2.74053868e-02 -2.71938276e-02  5.43624570e-04
 -1.71458777e-02  3.73468250e-02 -1.11119822e-03 -1.17769148e-02
 -3.07440795e-02  4.10605706e-02 -3.27414535e-02  3.63950208e-02
 -5.46337478e-02 -9.47653502e-03  2.90642586e-02 -6.01114659e-03
 -4.23317365e-02 -5.78626879e-02  1.61239691e-02  2.06005611e-02
  5.06034419e-02  2.14552451e-02  1.18449666e-02  5.26718562e-03
 -6.52440079e-03 -3.29455733e-03  1.94901954e-02  1.71508063e-02
  3.70117160e-03 -4.52904925e-02  3.28938570e-03 -9.34251677e-03
 -4.02319767e-02  3.05112428e-03 -4.09679413e-02  6.63880408e-02
 -2.72187851e-02 -1.94107220e-02  3.18184309e-03  1.28764799e-03
 -2.97046080e-02 -2.40596998e-02  1.99543405e-02  7.69901369e-03
  1.89729724e-02 -3.61911184e-03  2.99829654e-02  3.29828938e-03
  1.13943098e-02 -2.35727802e-02 -1.37910070e-02  1.25207016e-02
  5.25912158e-02 -1.80168005e-04 -4.43266556e-02 -1.35123022e-02
 -1.79121085e-02 -2.79439557e-02  2.35110745e-02  4.54693381e-03
 -1.33544430e-01  3.60775478e-02 -4.24941350e-03 -6.79007499e-03
 -6.26117690e-03  6.28143325e-02  2.94568706e-02 -6.42279536e-02
  6.31695148e-03 -1.73270125e-02  2.54671425e-02  1.23193173e-03
  4.52921633e-03 -6.61093593e-02 -3.13983811e-03 -2.53019948e-03
 -2.47068498e-02  1.90119706e-02  1.10595271e-01  4.22192924e-02
 -9.59139038e-03 -2.86450796e-02  2.37099919e-02  5.24059264e-03
 -1.29077642e-03  1.98162962e-02  6.87355036e-03 -3.91346440e-02
 -5.73025420e-02  1.07516870e-02 -2.07676422e-02  4.48465534e-02
 -2.88674962e-02 -1.19473785e-02 -7.99185690e-03  3.05405539e-02
 -1.26995668e-02  1.12130083e-02 -3.07377093e-02 -4.38823812e-02
  3.60398740e-02 -2.50368994e-02  6.06909730e-02  2.24654749e-02
  1.48144318e-02  4.94069569e-02  2.60929894e-02 -7.18699535e-03
  3.09723839e-02  5.93634835e-03  2.64265225e-03  1.01333447e-01
 -2.60191020e-02 -1.94574557e-02  3.10994368e-02 -9.46756918e-04
 -7.73090916e-03 -1.55830961e-02  4.22359072e-03  3.02338530e-03
 -1.14615858e-02  2.76707895e-02 -8.36371444e-03 -7.77952280e-03
 -1.65047012e-02 -1.37936557e-02  9.44214966e-03 -2.57372372e-02
  9.34128836e-03  1.27254173e-01  2.66939867e-02 -8.04515556e-03
 -3.88370156e-02  3.85814272e-02  9.44321323e-03 -1.62332710e-02
 -1.01412609e-02  4.41186205e-02  5.03603108e-02 -7.41883600e-03
 -5.38156461e-03  4.87564281e-02  5.50764892e-03 -3.25435400e-03
 -3.00826947e-03 -3.83356251e-02  2.66789738e-02 -4.86886501e-02
 -4.03326787e-02  1.85230952e-02 -3.75945009e-02  1.16655603e-02
  4.57839705e-02 -2.89050844e-02 -1.15085114e-02  1.05767539e-02
 -3.66557725e-02 -2.48488244e-02  6.40830025e-02  2.09442545e-02
 -4.76043634e-02 -3.77059728e-02 -3.23042981e-02  4.15267684e-02
  1.19585311e-02 -3.35728936e-02  3.67914923e-02  3.44443619e-02
  3.22724646e-03  1.94216631e-02 -2.94236764e-02  2.40040831e-02
  4.24020253e-02 -2.93922443e-02 -1.25564858e-02 -1.59439892e-02
 -1.72490682e-02 -2.01129802e-02  6.62402213e-02 -6.12685829e-02
 -6.29098266e-02 -1.97606217e-02 -6.18715100e-02  1.20935123e-02
  2.11596955e-02  7.63491448e-03  3.68559435e-02 -2.87126265e-02
 -1.81059521e-02  2.03276449e-03  4.24902886e-02  1.09525502e-01
 -3.31755430e-02 -2.24760151e-03  4.97868620e-02  1.89231783e-02
  3.46430093e-02  4.83687520e-02  2.30812542e-02  7.99511820e-02
 -3.60062122e-02 -8.87031481e-02 -4.33003716e-02  1.49839409e-02
  3.05749383e-03  2.14159917e-02 -1.95268891e-04 -8.62253383e-02
 -6.64693639e-02 -1.62019115e-02 -4.60269337e-04  6.43027425e-02
  2.90693007e-02 -3.65383290e-02 -1.75104719e-02 -1.83642134e-02
  1.08763101e-02  3.40821594e-02 -1.10469079e-02  1.92562230e-02
  2.41882429e-02 -1.00169457e-01  5.00502950e-03 -4.80382703e-02
 -2.44347397e-02 -2.57445909e-02  1.12671191e-02 -3.46992910e-02
 -1.02604795e-02 -2.06998829e-02 -4.97952402e-02  4.40746639e-03
 -1.31721990e-02  2.01728661e-02 -4.18215543e-02  2.89905574e-02
 -2.46366002e-02 -8.46611802e-03  7.14232167e-03 -4.50510681e-02
 -1.00026369e-01 -2.85879858e-02  5.10675237e-02 -2.83578713e-03
 -1.99816693e-02 -2.36324538e-02  1.96559937e-03 -4.51312289e-02
  4.39746119e-03  9.32291616e-03 -8.55997205e-03  1.10263405e-02
 -8.06731731e-03 -6.58512563e-02  1.62581280e-02 -1.66451056e-02
 -2.98138766e-04 -4.14398536e-02  2.25558076e-02  4.12497707e-02
  6.45447075e-02  4.71064169e-03 -1.20826233e-02  2.83550452e-02
 -2.83857267e-02  7.27859465e-03  1.77812241e-02  5.08023463e-02
  4.99011762e-02  1.52346650e-02  6.87036663e-03 -2.45943535e-02
  3.10525559e-02 -7.56926462e-02  2.29334049e-02 -4.05524746e-02
 -4.44981791e-02  3.91457975e-02 -1.79975815e-02  5.60539593e-05
 -4.03058715e-02  6.94202213e-03 -5.19223399e-02 -6.05754443e-02
 -1.00466765e-01 -1.17832003e-02 -4.72945347e-02 -3.03509366e-02
 -1.36418957e-02  4.26954366e-02 -2.40905229e-02  1.03403190e-02
  5.36931604e-02  5.22576012e-02 -8.50729346e-02  1.28876744e-02
  2.62863990e-02 -9.12963599e-02  2.09398270e-02 -1.04233287e-02
 -3.83501574e-02 -5.54611580e-03  4.65952680e-02  2.15254506e-04
 -1.07325576e-02 -2.20406000e-02 -3.76224890e-02 -5.19933030e-02
 -1.58237256e-02 -1.75754819e-02  4.98883426e-02 -1.22746043e-02
  2.08303593e-02 -1.15566887e-02  1.45754404e-02  2.23253178e-03
  5.13644181e-02 -1.54747227e-02  3.68775763e-02 -1.04725473e-02
  1.92868877e-02 -1.06532142e-01 -3.19822654e-02 -2.32057795e-02
 -1.75267924e-02  3.79935503e-02 -2.13285699e-03  3.18930000e-02
  1.17702261e-02  1.81738622e-02 -3.24360281e-03 -1.55045670e-02
 -2.32623313e-02  3.58847901e-02 -9.69896931e-03 -6.28403202e-02
  8.12547654e-03 -4.63158414e-02  3.40540297e-02  4.41878103e-02
 -7.85500109e-02 -3.07189636e-02  5.35752885e-02  4.17174697e-02
 -5.86441904e-03 -6.79818019e-02  5.23680560e-02 -2.28176769e-02
  3.71841080e-02  1.64524594e-03  1.21794986e-02  3.19620669e-02
 -2.40115379e-03  1.65183339e-02  2.39163376e-02  4.60017920e-02
  2.39126366e-02  5.71268126e-02 -9.87951760e-04  4.92325388e-02
  2.34280191e-02 -2.99983323e-02  5.08731231e-02  9.69367381e-03
 -1.20276241e-02 -2.17355154e-02 -7.77497515e-02 -1.33883329e-02
 -2.16683056e-02  2.97634192e-02 -4.29839119e-02  8.23412836e-03
  5.57172811e-04 -1.10042151e-02 -1.83298551e-02 -2.42426787e-02
 -1.08503108e-03  9.94633604e-03  3.48050147e-02  1.93826407e-02
  3.02756336e-02  1.66661590e-02  3.65679106e-03  2.91261729e-03
 -3.87375318e-02 -5.76332845e-02 -9.32419207e-03  6.13902062e-02
  1.18349576e-02  6.53877556e-02 -2.47816183e-02 -1.55245112e-02
  1.27385026e-02 -1.44191571e-02  3.07023488e-02  4.77246493e-02
  1.30430777e-02 -1.74888913e-02 -2.42386926e-02  4.91183512e-02
  2.56209578e-02  1.80270262e-02 -1.52887134e-02  4.24550064e-02
 -8.18800032e-02 -4.32163291e-02  1.85777880e-02 -1.89129412e-02
  2.32115928e-02  1.18951490e-02  9.23982635e-03 -5.53343259e-02
  2.71811280e-02 -2.09197924e-02 -1.75972376e-02  1.09052854e-02
  1.57882236e-02  1.78290810e-02  1.16688153e-03  1.47270542e-02
 -1.82641298e-03  2.82644182e-02 -2.77901832e-02 -6.48017153e-02
 -4.82442006e-02  8.35224465e-02 -2.68463921e-02 -8.77824053e-02
  6.97890222e-02  3.34591120e-02  5.45973666e-02  6.31528860e-03
 -7.41590979e-03  3.34694572e-02  2.88154893e-02  3.22647206e-02
  3.54319923e-02 -5.53319743e-03 -2.26037707e-02  6.08470254e-02
  5.56573905e-02 -1.94332507e-02 -1.04740737e-02 -1.04343355e-01
 -9.59245637e-02 -1.24589056e-02  6.67095557e-03 -6.97878360e-33
  2.74159331e-02  1.49907460e-02  6.28817268e-03 -3.06628104e-02
 -4.40071374e-02  3.84852290e-02  4.82746474e-02  3.96362804e-02
 -5.18021248e-02 -1.61240492e-02  3.61754489e-03  4.56989743e-03
  2.79353503e-02  7.91721139e-03  1.88892074e-02 -6.64001470e-03
 -1.05270576e-02  5.93615975e-03  3.18447198e-03  2.76654810e-02
 -3.05841700e-03 -1.55068208e-02 -2.35206261e-02  3.01412400e-02
  5.85066080e-02  3.16816829e-02  5.40158013e-04  4.44578789e-02
  1.92725845e-03 -5.97031191e-02 -9.70602874e-03 -3.95274535e-02
 -9.56430752e-03 -4.39229198e-02 -2.64988299e-02 -7.65145645e-02
  3.73797514e-03  3.31902988e-02  3.53950225e-02 -6.32138252e-02
 -1.10817293e-03  4.43717800e-02 -7.79874204e-03  2.04633642e-02
  5.06413244e-02 -2.09422968e-02 -8.96564871e-03  4.14459035e-02
  1.39736955e-03  6.31207526e-02 -1.59459952e-02  2.21753176e-02
 -2.97800507e-02  1.06356643e-01 -1.59731507e-02  3.34006362e-02
 -4.63969149e-02  1.76730345e-03  6.90591149e-03  8.65070673e-04
 -3.51054706e-02  8.78872909e-03  2.71361787e-02  3.19876373e-02
  3.69508099e-03  9.37207974e-03  5.75547442e-02  1.14667594e-01
  1.08976699e-02  2.04340760e-02 -7.64437439e-03  5.44733889e-02
 -4.98342849e-02  2.50077918e-02 -9.04431939e-02 -2.47273128e-02
 -1.86671577e-02 -9.01028328e-03 -8.40032026e-02  4.27348316e-02
 -2.89742486e-04  2.01576315e-02  1.01720430e-02  2.95046568e-02
  3.87201086e-02 -2.96865515e-02 -2.32874528e-02  3.95020135e-02
  2.83178389e-02 -7.94594362e-03 -3.20371650e-02  2.19288431e-02
  6.74194982e-03  3.34369298e-03  1.57483146e-02 -1.44173764e-02
 -5.40404730e-02 -4.25747217e-04 -6.14164537e-03  4.25223232e-04
 -7.26025626e-02  2.47686878e-02 -1.62062999e-02  5.37878424e-02
  2.74911951e-02  2.84831543e-02 -4.66988944e-02 -3.90577619e-03
 -1.65381201e-03 -5.90015668e-03 -3.43666822e-02  1.48431780e-02
  2.37865560e-02 -6.40977323e-02 -1.26975970e-02  2.28190329e-02
 -7.36305816e-03 -6.41562715e-02  5.59209206e-04 -5.59624424e-03
  1.37462625e-02 -5.53818829e-02 -6.69214129e-02  1.59419086e-02
 -5.02935499e-02 -2.73763947e-02 -3.03123146e-02 -7.50499684e-03
  1.44366100e-02 -4.36934866e-02  1.98046137e-02 -7.41143972e-02
  3.04317012e-07 -1.10184094e-02 -3.57299261e-02  4.14435342e-02
 -2.29619350e-02  1.44453086e-02 -2.25445479e-02 -6.54629320e-02
  3.76100987e-02 -6.41697040e-03  3.62359174e-02  6.72990084e-02
  1.07238805e-02 -1.18185654e-02 -2.76517998e-02  4.10337597e-02
 -6.36699349e-02 -4.18930873e-02 -3.22272703e-02 -2.26284079e-02
  2.30409689e-02  8.10057968e-02 -5.38772270e-02 -1.42504228e-02
 -1.80843845e-02  1.72602758e-02 -7.85793141e-02  9.67971631e-04
 -8.89056474e-02  4.86639887e-03 -4.40615155e-02  3.21095884e-02
  9.12686065e-03 -3.87530066e-02 -2.53500082e-02 -3.48159075e-02
 -2.36273538e-02 -4.07704301e-02  4.33665253e-02  3.54315676e-02
  1.12367477e-02  4.17448021e-03  3.73017928e-03  1.16078146e-02
  1.80445556e-02 -6.54346729e-03  4.77428501e-03 -3.19607332e-02
  1.05749471e-02 -3.89824919e-02  8.38996619e-02 -3.60809900e-02
  7.90825412e-02  2.42339652e-02  4.84039262e-02 -8.21426325e-03
  4.14278125e-03 -4.30570543e-02 -1.38133299e-02  2.50202371e-03
  3.59239541e-02 -1.30927842e-02 -5.41520957e-03 -1.34274662e-02
  1.53752081e-02  5.67718558e-02  6.37362599e-02 -2.79866788e-03
  2.63202966e-34  6.04315847e-03  6.03929337e-04  2.96166036e-02
 -9.99381300e-03  2.88144611e-02 -2.76565906e-02 -6.12875819e-02
  7.37086730e-03  1.62790157e-03 -1.40983798e-03 -4.25507240e-02]

In [57]:
## Vector embedding my fixed chunks

embedding_model.max_seq_length = 384  ## mpnet can process max 384 words for embedding
texts = [c["text_clean"] for c in chunks]
emb = embedding_model.encode(
    texts,
    batch_size=64,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True,
)
emb.shape

Batches:   0%|          | 0/138 [00:00<?, ?it/s]

(8817, 768)

In [59]:
import pandas as pd
df_meta = pd.DataFrame(chunks)
df_meta["embedding_dim"] = emb.shape[1]

df_meta["embedding"] = [v.astype(float).tolist() for v in emb]

row0 = df_meta.iloc[467].to_dict()
import json; print(json.dumps(row0, indent=2, ensure_ascii=False))

{
  "doc_id": "4b0038a49b90617ab24f1a1d0f1f697b",
  "filename": "AT&T_10K.pdf",
  "chunk_id": 14,
  "page_start": 4,
  "page_end": 5,
  "source_pages": [
    4,
    5
  ],
  "sentence_count": 10,
  "word_count": 181,
  "char_count": 1308,
  "page_token_count": 181,
  "text_clean": "1 AT&T Inc. Dollars in millions except per share amounts General We are a leading provider of telecommunications and technology services globally. The services and products that we offer vary by market and utilize various technology platforms in a range of geographies. Our reportable segments are organized as follows: The Communications segment provides wireless and wireline telecom and broadband services to consumers located in the United States and businesses globally. Our business strategies reflect integrated product offerings that cut across product lines and utilize shared assets. This segment contains the following business units: • Mobility provides nationwide wireless service and equipment. • Business Wireline provides advanced ethernet-based fiber services, fixed wireless services, IP Voice and managed professional services, as well as legacy voice and data services and related equipment, to business customers. • Consumer Wireline provides broadband services, including fiber connections that provide multi-gig services, and our fixed wireless access product (AT&T Internet Air or “AIA”) that provides internet services delivered over our 5G wireless network, to residential customers in select locations. Consumer Wireline also provides legacy telephony voice communication services.",
  "embedding_dim": 768,
  "embedding": [
    0.015316704288125038,
    0.0030749936122447252,
    -0.04560631886124611,
    -0.016059039160609245,
    -0.004915597382932901,
    0.03703832998871803,
    0.09982217103242874,
    -0.021609585732221603,
    -0.005327441729605198,
    -0.04172069951891899,
    -0.013790776021778584,
    -0.005411353427916765,
    0.05954587087035179,
    0.07029589265584946,
    0.00532047264277935,
    0.06324998289346695,
    -0.011734106577932835,
    0.04465781897306442,
    -0.022328346967697144,
    0.030542587861418724,
    0.015156298875808716,
    0.047723837196826935,
    0.018585816025733948,
    -0.03007548302412033,
    0.024806875735521317,
    -0.010773176327347755,
    0.06546550989151001,
    -0.008453283458948135,
    0.008822704665362835,
    -0.05256909877061844,
    0.06534299999475479,
    -0.08237863332033157,
    -0.02499064803123474,
    0.012848828919231892,
    2.584912181191612e-06,
    -0.0011826868867501616,
    -0.026741180568933487,
    0.019944682717323303,
    -0.04756813496351242,
    0.004176995251327753,
    -0.012784252874553204,
    0.10049504786729813,
    -0.01424402929842472,
    0.02929537370800972,
    -0.014522336423397064,
    0.04534628242254257,
    0.0379856713116169,
    0.004657164681702852,
    0.0060437764041125774,
    0.00823473185300827,
    -0.019613904878497124,
    -0.006510290317237377,
    -0.04494350031018257,
    0.007341563235968351,
    -0.09703782945871353,
    -0.04752214998006821,
    0.012134694494307041,
    0.01989055797457695,
    -0.026702703908085823,
    0.014036096632480621,
    0.05766202509403229,
    0.004187529906630516,
    0.03806381672620773,
    0.00322311301715672,
    0.023982135578989983,
    0.05241709202528,
    0.01404018048197031,
    -0.03440641239285469,
    -0.054225362837314606,
    0.003936639986932278,
    -0.020704064518213272,
    -0.0030016498640179634,
    0.018752170726656914,
    0.060921356081962585,
    -0.02134750410914421,
    -0.04980716481804848,
    -0.03342270106077194,
    -0.017033344134688377,
    -0.01832246407866478,
    0.025425948202610016,
    -0.032661572098731995,
    0.06625236570835114,
    -0.01840341091156006,
    -0.01639646664261818,
    -0.03868784010410309,
    0.03815048933029175,
    -0.005034153815358877,
    -0.001084153656847775,
    -0.026090150699019432,
    0.005783915054053068,
    0.011297598481178284,
    -0.04030238091945648,
    0.040297072380781174,
    -0.040417976677417755,
    0.03632053732872009,
    0.012772752903401852,
    0.017125872895121574,
    -0.050089530646800995,
    -0.015531874261796474,
    -0.026727598160505295,
    0.04238608106970787,
    -0.0037040533497929573,
    -0.026579435914754868,
    0.01603146642446518,
    -0.01014025416225195,
    -0.02464635670185089,
    0.011919067241251469,
    -0.0693555548787117,
    -0.0386698879301548,
    0.05129050463438034,
    0.03639501705765724,
    -0.034273162484169006,
    -0.033571451902389526,
    0.10720428079366684,
    -0.011090410873293877,
    -8.449853339698166e-05,
    -0.030819229781627655,
    0.026656322181224823,
    -0.022610312327742577,
    -0.001483680447563529,
    -0.0009217502665705979,
    -0.02208475023508072,
    0.004222488962113857,
    -0.057946864515542984,
    -0.020502980798482895,
    -0.0023542989511042833,
    -0.06071360781788826,
    0.043542638421058655,
    0.02118910476565361,
    -0.05310358107089996,
    -0.0008563385927118361,
    -0.02623393014073372,
    0.03715807572007179,
    -0.019551463425159454,
    -0.005508033558726311,
    -0.0517500601708889,
    -0.00015331752365455031,
    -0.012199128977954388,
    -0.01837986893951893,
    -0.04043171554803848,
    0.04373578354716301,
    -0.0544300302863121,
    -0.08416014909744263,
    0.018127230927348137,
    0.015151956118643284,
    0.008738777600228786,
    -0.0005964000592939556,
    0.04256090521812439,
    -0.011960138566792011,
    0.011744009330868721,
    0.006830224301666021,
    0.0014337062602862716,
    0.009207010269165039,
    -0.01577179692685604,
    0.06881497800350189,
    0.002195873763412237,
    0.1111871674656868,
    -0.036081694066524506,
    -0.03497499227523804,
    -0.018068883568048477,
    0.01588588021695614,
    -0.027964448556303978,
    -0.07094570249319077,
    -0.019521968439221382,
    0.01358381099998951,
    0.033222541213035583,
    0.05352717265486717,
    -0.0003154515870846808,
    -0.07821602374315262,
    -0.07390251010656357,
    -0.019902722910046577,
    0.016830360516905785,
    -0.007026141509413719,
    0.026368480175733566,
    0.03357061371207237,
    0.00943162851035595,
    0.05378720909357071,
    0.055192381143569946,
    -0.06535571068525314,
    0.037508316338062286,
    -0.03745434433221817,
    -0.13883529603481293,
    -0.009287540800869465,
    0.029929056763648987,
    -0.04883405566215515,
    0.007476519793272018,
    0.03386286646127701,
    0.03493016958236694,
    -0.028800418600440025,
    -0.010370747186243534,
    0.006275004241615534,
    -0.006339675281196833,
    -0.056513573974370956,
    0.013629727996885777,
    -0.019257351756095886,
    0.01774527132511139,
    0.006538272835314274,
    0.01057841069996357,
    -0.04466562718153,
    0.05359552800655365,
    -0.024816039949655533,
    -0.031440407037734985,
    0.00226438045501709,
    0.052628044039011,
    -0.018733493983745575,
    0.028944943100214005,
    -0.029901746660470963,
    -0.014653220772743225,
    -0.01001704204827547,
    0.03371194377541542,
    0.006594014819711447,
    0.022873062640428543,
    -0.05607489496469498,
    0.009170284494757652,
    0.04235367104411125,
    0.032093413174152374,
    0.031817175447940826,
    0.07867513597011566,
    -0.07969336211681366,
    0.057593151926994324,
    -0.043102506548166275,
    0.026084845885634422,
    0.03477805107831955,
    -0.03075570985674858,
    0.020363904535770416,
    0.0021696798503398895,
    -0.0005696604494005442,
    0.018373792991042137,
    -0.03529169782996178,
    0.0033628945238888264,
    -0.0024155040737241507,
    -0.004629232455044985,
    -0.025649573653936386,
    -0.026117179542779922,
    -0.024457082152366638,
    0.03481156378984451,
    0.01816677302122116,
    0.1433234065771103,
    -0.0013212570920586586,
    -0.01101679727435112,
    0.014858763664960861,
    -0.046592120081186295,
    0.060792528092861176,
    -0.01542883925139904,
    0.04821031168103218,
    -0.023577064275741577,
    -0.0014838941860944033,
    0.007655158638954163,
    -0.006639015395194292,
    0.03630652651190758,
    0.0023169326595962048,
    -0.00018289514991920441,
    -0.021224690601229668,
    0.0027312871534377337,
    -0.010341214947402477,
    -0.024656416848301888,
    -0.03683403879404068,
    0.05371280387043953,
    -0.0019124482059851289,
    0.022254738956689835,
    0.01329218503087759,
    -0.04594067856669426,
    -0.05107983201742172,
    -0.010816498659551144,
    -0.04246441647410393,
    0.023815151304006577,
    0.04346112534403801,
    0.006700810045003891,
    0.004170715808868408,
    -0.01898868940770626,
    0.026093685999512672,
    0.04293880984187126,
    0.037009578198194504,
    -0.027255922555923462,
    -0.005046859383583069,
    0.028064478188753128,
    -0.013936360366642475,
    0.0022021974436938763,
    0.007061611860990524,
    0.017810288816690445,
    0.0735170841217041,
    -0.0834338590502739,
    -0.04975592717528343,
    -0.02130853570997715,
    0.002620679559186101,
    -0.02505147084593773,
    0.03188136965036392,
    -0.07611192762851715,
    -0.045382145792245865,
    -0.08607149869203568,
    -0.00561019591987133,
    -0.010454006493091583,
    -0.053135018795728683,
    -0.051703035831451416,
    0.019973453134298325,
    -0.003390207653865218,
    -0.01768297702074051,
    0.004519238136708736,
    0.026783693581819534,
    0.022282779216766357,
    -0.01276595052331686,
    0.001528622000478208,
    -0.019004279747605324,
    -0.0008243334013968706,
    -0.03100658766925335,
    0.0012466638581827283,
    0.010510861873626709,
    0.009815793484449387,
    0.008894079364836216,
    0.059731047600507736,
    0.05117756500840187,
    0.04370083287358284,
    -0.013453926891088486,
    -0.01480613648891449,
    -0.005225033964961767,
    -0.009526429697871208,
    -0.056451600044965744,
    0.026516903191804886,
    -0.023934895172715187,
    0.07917502522468567,
    0.04241776093840599,
    0.02254447154700756,
    0.029024366289377213,
    0.03201725333929062,
    0.022448943927884102,
    -0.003765129018574953,
    -0.040015898644924164,
    0.013878080062568188,
    -0.011288330890238285,
    -0.08320652693510056,
    0.01855471543967724,
    -0.004353026859462261,
    -0.05983470752835274,
    0.07620149105787277,
    0.04527935013175011,
    -0.02346908673644066,
    -0.057202987372875214,
    0.010602657683193684,
    -0.014638914726674557,
    -0.02216072753071785,
    -0.018822336569428444,
    -0.002553637372329831,
    0.01689823530614376,
    0.026685087010264397,
    0.03098265826702118,
    -0.05672788619995117,
    0.04502850025892258,
    0.005419569090008736,
    -0.0054648942314088345,
    -0.02163024991750717,
    -0.00496266596019268,
    -0.003053459106013179,
    -0.03391392529010773,
    0.03305840864777565,
    -0.003867038758471608,
    -0.024708598852157593,
    -0.02617591992020607,
    -0.006645580288022757,
    -0.03854391351342201,
    0.04097115993499756,
    0.033459313213825226,
    -0.051822252571582794,
    -0.004044428467750549,
    -0.0035370145924389362,
    0.013661968521773815,
    0.04087115451693535,
    0.011971274390816689,
    -0.008922604843974113,
    -0.048885948956012726,
    -0.015964137390255928,
    -0.00979572907090187,
    0.03878209367394447,
    0.01801161654293537,
    -0.024280300363898277,
    -0.020758919417858124,
    0.009427444078028202,
    -0.017857490107417107,
    0.04374091699719429,
    0.0023284212220460176,
    0.030615326017141342,
    0.04531548172235489,
    -0.08429188281297684,
    0.08423320204019547,
    -0.025679953396320343,
    -0.027783840894699097,
    0.048001959919929504,
    -0.03507763892412186,
    -0.07599370926618576,
    -0.055598184466362,
    0.008237911388278008,
    0.0049754041247069836,
    0.09264937043190002,
    -0.0320754274725914,
    0.07017118483781815,
    0.004332938697189093,
    0.011078780516982079,
    0.052916232496500015,
    -0.013241035863757133,
    -0.03001391515135765,
    -0.007366373669356108,
    0.032759442925453186,
    -0.08084449917078018,
    0.04718006029725075,
    -0.030181633308529854,
    0.007049226202070713,
    -0.038528576493263245,
    0.011930685490369797,
    0.014838950708508492,
    -0.027569545432925224,
    0.029854383319616318,
    -0.007999145425856113,
    -0.08968187123537064,
    0.009598380886018276,
    0.022182859480381012,
    -0.00993258971720934,
    -0.048147618770599365,
    -0.004784542601555586,
    0.07244692742824554,
    0.04885810986161232,
    0.015834400430321693,
    0.05737564340233803,
    -0.018247952684760094,
    -0.0222767423838377,
    -0.039970435202121735,
    0.030902260914444923,
    0.0337664894759655,
    0.007290369365364313,
    -0.011680004186928272,
    -0.004195773974061012,
    -0.05410487577319145,
    -0.028549620881676674,
    -0.04121150076389313,
    -0.054004885256290436,
    0.028006883338093758,
    -0.011426584795117378,
    -0.03781909495592117,
    0.0703752264380455,
    -0.022387102246284485,
    -0.07173431664705276,
    -0.023566940799355507,
    0.02117121033370495,
    -0.007932067848742008,
    -0.0029808497056365013,
    0.029539665207266808,
    -0.0661851167678833,
    0.037013571709394455,
    0.01346573606133461,
    0.06279507279396057,
    -0.08218535035848618,
    0.035422541201114655,
    0.0006959704332984984,
    -0.010435281321406364,
    0.025433266535401344,
    -0.07594653218984604,
    -0.027959834784269333,
    -0.024933621287345886,
    -0.012608425691723824,
    -0.0445636585354805,
    0.019051432609558105,
    0.037538979202508926,
    -0.029041152447462082,
    0.022934697568416595,
    0.028649182990193367,
    -0.009222215041518211,
    0.05339626967906952,
    -0.00660994928330183,
    0.014188910834491253,
    -0.050843071192502975,
    -0.01328958384692669,
    0.026530854403972626,
    0.0025735367089509964,
    0.009094501845538616,
    0.040635161101818085,
    -0.024100838229060173,
    -0.011958030983805656,
    -0.001996732084080577,
    -0.03083079867064953,
    -0.04846794530749321,
    0.00990400742739439,
    0.04616587609052658,
    0.005222725216299295,
    -0.012277578935027122,
    0.03168970346450806,
    -0.030284015461802483,
    -0.011126036755740643,
    0.02305697090923786,
    0.032816965132951736,
    0.010968377813696861,
    0.009850851260125637,
    -0.0472337007522583,
    0.006872638128697872,
    -0.037169866263866425,
    0.014981843531131744,
    0.0004298349958844483,
    0.03647990524768829,
    0.0021948027424514294,
    0.05140528455376625,
    0.013475320301949978,
    -0.08770966529846191,
    -0.01864813268184662,
    -0.03301612287759781,
    0.030356699600815773,
    0.011442886665463448,
    0.020137211307883263,
    0.007206518668681383,
    0.025871651247143745,
    -0.01840899884700775,
    0.00656522810459137,
    0.004503857810050249,
    0.014348652213811874,
    -0.05334444344043732,
    0.021397965028882027,
    0.026002496480941772,
    -0.009845254942774773,
    0.030398020520806313,
    0.07641210407018661,
    -0.09805664420127869,
    0.017213499173521996,
    0.03976194187998772,
    -0.03912651166319847,
    0.031867288053035736,
    0.025569701567292213,
    -0.0126345818862319,
    0.00802036002278328,
    0.001191543648019433,
    0.03406932204961777,
    0.004437392111867666,
    0.002590364310890436,
    0.03502076119184494,
    0.007077048532664776,
    0.03047558106482029,
    0.008245214819908142,
    -0.07937462627887726,
    0.008783292956650257,
    -0.03652193769812584,
    -0.021824650466442108,
    0.0279406551271677,
    0.018369270488619804,
    0.015406900085508823,
    -0.021247535943984985,
    -0.000419658055761829,
    0.025908447802066803,
    -0.031738534569740295,
    -0.018925411626696587,
    0.05204940587282181,
    -0.054203130304813385,
    -0.03007798083126545,
    0.03321617841720581,
    0.012146231718361378,
    -0.03535765781998634,
    0.030283348634839058,
    -0.022353606298565865,
    -0.07618679851293564,
    0.01599491387605667,
    0.011691546998918056,
    -7.811004208212617e-33,
    -0.028733115643262863,
    -0.0026804329827427864,
    0.014286481775343418,
    0.030744915828108788,
    -0.025682559236884117,
    0.048659663647413254,
    0.026161279529333115,
    0.019768210127949715,
    -0.07164894789457321,
    -0.04133761301636696,
    -0.0382203571498394,
    0.026202166453003883,
    0.02594052255153656,
    -0.0015889707719907165,
    -0.008459741249680519,
    -0.00013365138147491962,
    0.018622394651174545,
    -0.020882954820990562,
    0.010285166092216969,
    0.01950373873114586,
    -0.04446658864617348,
    -0.009368534199893475,
    0.010338339023292065,
    0.009083367884159088,
    0.026781238615512848,
    -0.009734557941555977,
    -0.021222462877631187,
    -0.02937336638569832,
    -0.0011165993055328727,
    0.006466127932071686,
    -0.03904001787304878,
    0.006057922728359699,
    0.013077828101813793,
    -0.04588741436600685,
    0.011331608518958092,
    0.07630620151758194,
    -0.04161519184708595,
    -0.002690644236281514,
    0.0028064202051609755,
    0.00216898531652987,
    0.01146964356303215,
    -0.018521446734666824,
    0.019772984087467194,
    0.012462684884667397,
    -0.0185118205845356,
    -0.027745060622692108,
    -0.00731127941980958,
    0.009010888636112213,
    0.03470877930521965,
    0.0038658876437693834,
    0.03629083186388016,
    -0.042477596551179886,
    -0.028902404010295868,
    0.07799623906612396,
    -0.001413055113516748,
    -0.08050938695669174,
    -0.029951848089694977,
    0.009102721698582172,
    7.182866102084517e-05,
    -0.007205592468380928,
    0.03123071976006031,
    0.039010632783174515,
    -0.005546338856220245,
    -0.03379717096686363,
    -0.01919480599462986,
    -0.003906752448529005,
    -0.06733855605125427,
    0.027135197073221207,
    -0.010652586817741394,
    -0.026482809334993362,
    -0.01371035911142826,
    0.08374636620283127,
    -0.04623113200068474,
    -0.056966520845890045,
    -0.031836144626140594,
    -0.021123327314853668,
    0.016393452882766724,
    0.01172021497040987,
    0.06299266219139099,
    0.020283034071326256,
    -0.007911142893135548,
    -0.016158562153577805,
    0.027545616030693054,
    0.02286357991397381,
    0.047251686453819275,
    -0.056647639721632004,
    -0.024236762896180153,
    -0.05150536447763443,
    0.013241421431303024,
    0.004951827693730593,
    -0.013072851113975048,
    0.07005542516708374,
    -0.0040090084075927734,
    -0.033442433923482895,
    -0.026320815086364746,
    -0.07643144577741623,
    0.012379632331430912,
    0.06750121712684631,
    0.006167586427181959,
    -0.024647759273648262,
    -0.018964780494570732,
    0.04735945537686348,
    -0.03605244681239128,
    0.046976443380117416,
    -0.037635378539562225,
    -0.013508226722478867,
    0.043481044471263885,
    -0.0169729832559824,
    -0.055279288440942764,
    0.039839740842580795,
    0.02372615970671177,
    0.008691268041729927,
    0.037660688161849976,
    -0.026450619101524353,
    -0.0024587088264524937,
    0.0035946837160736322,
    0.02707812935113907,
    0.035863932222127914,
    -0.04192008450627327,
    -0.02728961408138275,
    0.011044829152524471,
    -0.007774590514600277,
    -0.0587138868868351,
    -0.0011603947496041656,
    -0.08183020353317261,
    0.007049878127872944,
    -0.04090788960456848,
    -0.010708928108215332,
    0.03118133544921875,
    -0.010048839263617992,
    -0.011514727957546711,
    0.0012241866206750274,
    3.258364529301616e-07,
    0.016785375773906708,
    0.01153794676065445,
    0.05001180246472359,
    0.12659959495067596,
    0.03248711675405502,
    -0.026235749945044518,
    0.022732317447662354,
    -0.0235245730727911,
    0.014691411517560482,
    0.014750334434211254,
    0.05099768564105034,
    -0.04660271108150482,
    -0.010067157447338104,

In [65]:
import numpy as np, faiss

emb_unit = emb / np.linalg.norm(emb, axis=1, keepdims=True)

d = emb_unit.shape[1]  # 768
index = faiss.IndexHNSWFlat(d, 32)
index.hnsw.efConstruction = 200
index.add(emb_unit)

# saving the faiss bse
faiss.write_index(index, "/content/drive/MyDrive/10k_processed/mpnet_hnsw.faiss")

In [66]:
import numpy as np, pandas as pd, faiss, os


os.makedirs("/content/drive/MyDrive/10k_processed", exist_ok=True)
## ID mapping along with FAISS INDEX fro future citation issue
ids = np.arange(len(emb_unit), dtype='int64')
base = faiss.IndexHNSWFlat(emb_unit.shape[1], 32)
base.hnsw.efConstruction = 200
index = faiss.IndexIDMap2(base)
index.add_with_ids(emb_unit, ids)

faiss.write_index(index, "/content/drive/MyDrive/10k_processed/mpnet_hnsw.faiss")

# Save metadata for citation
meta = pd.DataFrame([{
    "id": i,
    "doc_id": c.get("doc_id"),
    "filename": c.get("filename"),
    "page_start": c.get("page_start"),
    "page_end": c.get("page_end"),
    "text_clean": c.get("text_clean", "")
} for i, c in enumerate(chunks)])
meta.to_parquet("/content/drive/MyDrive/10k_processed/chunk_meta.parquet", index=False)

Query from faiss index mapper

In [67]:
# loading index, embedding and meta data for citaion
import faiss, pandas as pd
from sentence_transformers import SentenceTransformer

INDEX_PATH = "/content/drive/MyDrive/10k_processed/mpnet_hnsw.faiss"
META_PATH  = "/content/drive/MyDrive/10k_processed/chunk_meta.parquet"

index = faiss.read_index(INDEX_PATH)
meta  = pd.read_parquet(META_PATH)

embedder = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
embedder.max_seq_length = 384

In [68]:
## Retriev from the index mapper along with citation

def retrieve_with_citations(query: str, k: int = 8):
    q = embedder.encode([query], normalize_embeddings=True)  # (1, 768)
    D, I = index.search(q, k)
    hits = []
    for rank, (lab, score) in enumerate(zip(I[0], D[0]), 1):
        row = meta.loc[meta["id"] == int(lab)].iloc[0]
        pages = (row.get("page_start"), row.get("page_end"))
        hits.append({
            "rank": rank,
            "score": float(score),
            "id": int(lab),
            "filename": row.get("filename"),
            "page_start": int(pages[0]) if pd.notna(pages[0]) else None,
            "page_end": int(pages[1]) if pd.notna(pages[1]) else None,
            "text": row.get("text_clean", "")
        })
    return hits

def build_context(hits, max_chunks=5):
    blocks = []
    for h in hits[:max_chunks]:
        if h["page_start"] and h["page_end"]:
            cite = f"[{h['filename']} pp.{h['page_start']}–{h['page_end']}]"
        else:
            cite = f"[{h['filename']}]"
        blocks.append(f"{cite}\n{h['text']}")
    return "\n\n".join(blocks)

In [69]:
# Loading the finetuned model
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_ID = "iamAbhishek01/mistral7b-finance-merged"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/587k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.57G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [70]:
## Prompt Engineering for faiss quering
def answer_with_rag(question: str, k: int = 8, max_chunks: int = 5, max_new_tokens: int = 400):
    #retrieve
    hits = retrieve_with_citations(question, k=k)
    context = build_context(hits, max_chunks=max_chunks)

    #build prompt
    prompt = f"""You are a finance assistant. Answer strictly from the CONTEXT.
If the context is insufficient, say you don't know.
Always cite sources in brackets using filename and page range.

QUESTION:
{question}

CONTEXT:
{context}

ANSWER:"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.2,
            top_p=0.9,
            do_sample=False
        )
    text = tokenizer.decode(out[0], skip_special_tokens=True)

    answer = text.split("ANSWER:")[-1].strip()
    return answer, hits

In [71]:
q = "What risk factors did Apple highlight for fiscal year 2024?"
answer, hits = answer_with_rag(q, k=12, max_chunks=5, max_new_tokens=350)
print("ANSWER:\n", answer, "\n")
print("CITATIONS:")
for h in hits[:5]:
    ps = f"pp.{h['page_start']}–{h['page_end']}" if h['page_start'] and h['page_end'] else "pages n/a"
    print(f"- {h['filename']} ({ps})  score={h['score']:.3f}")

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
/usr/local/lib/python3.12/dist-packages/bitsandbytes/autograd/_functions.py:181: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

ANSWER:
 The Company’s financial position and growth are subject to risks related to global economic, political, and legal developments, as well as commercial and consumer risks such as acquisitions, dispositions, joint ventures, and share-based compensation.

CITATIONS:
- apple_2024_10K.pdf (pp.7–8)  score=0.576
- General_Electric_10K.pdf (pp.38–39)  score=0.643
- apple_2024_10K.pdf (pp.24–24)  score=0.667
- apple_2024_10K.pdf (pp.50–51)  score=0.683
- apple_2024_10K.pdf (pp.27–28)  score=0.701

## Question from the documents

1.
Q: Since when has Alan R. Mulally served on the company’s Board of Directors?
A: Since July 2014.

2.
Q: What roles did Alan hold at Ford Motor Company, and during what years?
A: President and Chief Executive Officer from September 2006 through June 2014, and he was also a member of Ford’s board and served on its finance committee during the same period.

3.
Q: Which global automotive company did Alan lead as CEO?
A: Ford Motor Company.

4.
Q: Before Ford, what was Alan’s title at Boeing between March 2001 and September 2006?
A: Executive Vice President of The Boeing Company and President and Chief Executive Officer of Boeing Commercial Airplanes, Inc.

5.
Q: On which executive body at Boeing did Alan serve?
A: The Boeing Executive Council.

6.
Q: What Boeing division did Alan lead prior to his Commercial Airplanes role?
A: Boeing’s space and defense business (as President).

7.
Q: Name two government or advisory bodies Alan served on outside his corporate roles.
A: He co-chaired the Washington Competitiveness Council and sat on the U.S. Air Force Scientific Advisory Board.
(Other valid picks from the paragraph: advisory boards of NASA, University of Washington, University of Kansas, MIT.)

8.
Q: List three universities whose advisory boards included Alan.
A: University of Washington, University of Kansas, and the Massachusetts Institute of Technology.

9.
Q: Did Alan serve on Ford’s finance committee? If so, when?
A: Yes, from September 2006 through June 2014.

10.
Q: What time span did Alan serve as CEO of Boeing Commercial Airplanes?
A: From March 2001 to September 2006.

11. (multi-hop)
Q: Was Alan simultaneously on Ford’s board and serving as Ford’s CEO?
A: Yes. From September 2006 through June 2014 he was both on Ford’s board (and its finance committee) and served as President and CEO.

12. (negative control)
Q: Did the paragraph say Alan worked at General Motors?
A: No. It mentions Ford and Boeing, not General Motors.

In [72]:
qa_items = [
    ("Since when has Alan R. Mulally served on the company’s Board of Directors?", "since july 2014"),
    ("What roles did Alan hold at Ford Motor Company, and during what years?", "president and chief executive officer from september 2006 through june 2014"),
    ("Which global automotive company did Alan lead as CEO?", "ford motor company"),
    ("What was Alan’s title at Boeing between March 2001 and September 2006?", "executive vice president of the boeing company and president and chief executive officer of boeing commercial airplanes"),
    ("On which executive body at Boeing did Alan serve?", "boeing executive council"),
    ("What Boeing division did Alan lead prior to his Commercial Airplanes role?", "boeing’s space and defense business"),
    ("Name two government or advisory bodies Alan served on outside his corporate roles.", "washington competitiveness council; u.s. air force scientific advisory board"),
    ("List three universities whose advisory boards included Alan.", "university of washington; university of kansas; massachusetts institute of technology"),
    ("Did Alan serve on Ford’s finance committee? If so, when?", "yes; september 2006 through june 2014"),
    ("What time span did Alan serve as CEO of Boeing Commercial Airplanes?", "march 2001 to september 2006"),
    ("Was Alan simultaneously on Ford’s board and serving as Ford’s CEO?", "yes"),
    ("Did the paragraph say Alan worked at General Motors?", "no"),
]


def _norm(s: str) -> str:
    s = s or ""
    s = s.lower()
    s = re.sub(r"\s+", " ", s).strip()
    return s

results = []
for i, (q, gold) in enumerate(qa_items, 1):
    ans, hits = answer_with_rag(q, k=12, max_chunks=5, max_new_tokens=300)
    norm_ans  = _norm(ans)
    norm_gold = _norm(gold)
    ok = norm_gold in norm_ans
    top_cite = f"{hits[0]['filename']} pp.{hits[0]['page_start']}–{hits[0]['page_end']}" if hits else "n/a"
    results.append({
        "idx": i,
        "question": q,
        "expected_contains": gold,
        "answer": ans,
        "match": ok,
        "top_citation": top_cite,
        "top_score": hits[0]['score'] if hits else None
    })

df_res = pd.DataFrame(results)
pd.set_option("display.max_colwidth", 180)
display(df_res)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

,idx,question,expected_contains,answer,match,top_citation,top_score
0,1,Since when has Alan R. Mulally served on the company’s Board of Directors?,since july 2014,"Alan R. Mulally has served as a member of the Board of Directors since July 2014, and he has served as the Executive Vice President and Chief Financial Officer from March 1991 ...",True,AIG_10K.pdf pp.6–6,0.543645
1,2,"What roles did Alan hold at Ford Motor Company, and during what years?",president and chief executive officer from september 2006 through june 2014,"Alan served as President and Chief Executive Officer from September 2006 to June 2014, and as Executive Vice President from February 5, 2025 to February 5, 2024.",False,AIG_10K.pdf pp.6–6,0.796068
2,3,Which global automotive company did Alan lead as CEO?,ford motor company,"Alan R. Mulally served as CEO from July 2014 to September 2014, and as President and Chief Executive Officer from September 2006 to September 2014. He also served as co-chair o...",False,AIG_10K.pdf pp.6–6,0.728023
3,4,What was Alan’s title at Boeing between March 2001 and September 2006?,executive vice president of the boeing company and president and chief executive officer of boeing commercial airplanes,"The sum of each quarter’s per-share amount may not equal the total per-share amount for the respective year, and the sum of per-share amounts from continuing operations and dis...",False,AIG_10K.pdf pp.6–6,0.666628
4,5,On which executive body at Boeing did Alan serve?,boeing executive council,"Alan served as President, Server and Tools from 2011 to 2013, and Senior Vice President, Search, Portal, and Advertising from 2009 to 2011. He also served as Executive Vice Pre...",False,AIG_10K.pdf pp.6–6,0.643922
5,6,What Boeing division did Alan lead prior to his Commercial Airplanes role?,boeing’s space and defense business,[AIG_10K.pdf pp.10–10]\nAir Force Scientific Advisory Board. Paul S. Otellini • Global business leadership and extensive financial and management expertise as former President ...,False,AIG_10K.pdf pp.6–6,0.805707
6,7,Name two government or advisory bodies Alan served on outside his corporate roles.,washington competitiveness council; u.s. air force scientific advisory board,"Alan R. Mulally has served as an Executive Vice President since March 2017, and as Chief Accounting Officer since April 2019. He also served as co-chair of the Washington Compe...",False,AIG_10K.pdf pp.6–6,0.912262
7,8,List three universities whose advisory boards included Alan.,university of washington; university of kansas; massachusetts institute of technology,"The main function of the Audit Committee is to oversee accounting and financial reporting processes. This includes selecting and hiring independent auditors, developing financi...",False,AIG_10K.pdf pp.10–10,0.968042
8,9,"Did Alan serve on Ford’s finance committee? If so, when?",yes; september 2006 through june 2014,"The costco-chair of the Office of the Chair and Chief Executive Officer, and a member of the Sustainability, Innovation and Policy Committee of the Board of Directors.",False,AIG_10K.pdf pp.6–6,0.898487
9,10,What time span did Alan serve as CEO of Boeing Commercial Airplanes?,march 2001 to september 2006,"Alan served as President of Boeing Commercial Airplanes, Inc. and President and Chief Operating Officer of Ford Motor Company and President and Chief Operating Officer of Avio ...",False,AIG_10K.pdf pp.6–6,0.675211
10,11,Was Alan simultaneously on Ford’s board and serving as Ford’s CEO?,yes,Alan is a member of the Board of Directors and serves as Executive Vice President. He also serves as co-chair of the Washington Competitiveness Council and sits on the advisory...,False,AIG_10K.pdf pp.6–6,0.805064
11,12,Did the paragraph say Alan worked at General Motors?,no,"Alan worked at General Motors for 10 years, and his success in the industry is attributed to his ability to timely fund and introduce new and improved vehicle models, such as E...",False,General_Motors_10K.pdf pp.15–16,0.990213

## Evaluation Metrics :: RAGAS

In [88]:

## Questions
questions = [
    "What major risks does Alphabet cite from operating internationally and from financial exposures?",
    "Summarize Alan R. Mulally’s service on the company’s board and his prior leadership at Ford and Boeing, including dates, committee memberships, and key advisory roles.",
    "Summarize the key governance and career details mentioned: John’s planned resignation from Stanford, Ann Mather’s current board seats and committee roles, her prior directorships and executive experience, her education and credential, and Alan R. Mulally’s board service with dates",
    "In brief, what does Ford’s global facilities footprint and ownership/lease mix look like as of Dec 31, 2024?",
    "Briefly explain how Microsoft measures fair value for Level 2 and Level 3 items, how it values equity investments without readily determinable fair values, and its policy for property and equipment.",
    "What macroeconomic and regulatory factors could materially impact Walmart, and how might they affect Walmart’s demand, margins, costs, inventory, suppliers, and partnerships?",
    "In brief, what were Pfizer’s key 2024 items (gains, dividends, charges) and what intangible-asset impairments did it record, including fair-value levels and valuation method?",
    "What does Ford’s 2024 Form 10-K cover and how is the company classified, including listing details?"

]
import pandas as pd

def ask_batch_to_df(
    questions,
    k=12,
    max_chunks=5,
    max_new_tokens=350,
):
    rows = []
    for q in questions:
        try:
            ans, _hits = answer_with_rag(q, k=k, max_chunks=max_chunks, max_new_tokens=max_new_tokens)
            ans = (ans or "").strip()
        except Exception as e:
            ans = f"[ERROR] {e}"
        rows.append({"question": q, "prediction": ans})
    return pd.DataFrame(rows)

# run
df_preds = ask_batch_to_df(questions, k=12, max_chunks=5, max_new_tokens=350)
df_preds

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

,question,prediction
0,What major risks does Alphabet cite from operating internationally and from financial exposures?,Alphabet Inc.
1,"Summarize Alan R. Mulally’s service on the company’s board and his prior leadership at Ford and Boeing, including dates, committee memberships, and key advisory roles.","[aIG_10K.pdf pp.107–107]\nFORD MOTOR COMPANY BY: /s/ Mark Kosman Mark Kosman, Chief Accounting Officer (principal accounting officer) Date: February 5, 2025 Pursuant to the req..."
2,"Summarize the key governance and career details mentioned: John’s planned resignation from Stanford, Ann Mather’s current board seats and committee roles, her prior directorshi...","John has served as the President of Stanford University since September 2000, and he has also served as a member of the Board of Directors of Cisco Systems, Inc. and as the Cha..."
3,"In brief, what does Ford’s global facilities footprint and ownership/lease mix look like as of Dec 31, 2024?",[ERROR] CUDA out of memory. Tried to allocate 618.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 52.12 MiB is free. Process 167004 has 14.69 GiB memory in use. Of the...
4,"Briefly explain how Microsoft measures fair value for Level 2 and Level 3 items, how it values equity investments without readily determinable fair values, and its policy for p...","Microsoft uses the market approach, which includes three levels of inputs and liabilities in active markets, and observable inputs for the asset or liability."
5,"What macroeconomic and regulatory factors could materially impact Walmart, and how might they affect Walmart’s demand, margins, costs, inventory, suppliers, and partnerships?","Walmart Inc. Consolidated Statements of Income Fiscal Years Ended January 31, (Dollar amounts and retail square feet in millions) 2025 2024 2023 Walmart Inc. Consolidated State..."
6,"In brief, what were Pfizer’s key 2024 items (gains, dividends, charges) and what intangible-asset impairments did it record, including fair-value levels and valuation method?",[ERROR] CUDA out of memory. Tried to allocate 3.02 GiB. GPU 0 has a total capacity of 14.74 GiB of which 2.46 GiB is free. Process 167004 has 12.28 GiB memory in use. Of the al...
7,"What does Ford’s 2024 Form 10-K cover and how is the company classified, including listing details?","Ford’s 2024 Form 10-K is $48,960,272,506,076 shares of Common Stock, and $38,497,761 shares of Total Stock."

In [89]:
ground_truth = [
    "Alphabet flags anti-bribery compliance (the FCPA and comparable local laws), cross-country labor and HR differences that add operational complexity, and foreign-currency risk that can depress revenue and earnings even with partial hedging (which itself introduces risk). It also notes exposure to changes in the fair value of its debt and equity investments due to liquidity, credit, market moves, interest rates, and regulation, and says several items—non-marketable securities, certain stock-based awards, and some acquisition assets/liabilities—require subjective fair-value estimates.",
    "Alan R. Mulally has served on the company’s Board of Directors since July 2014. He was President and CEO of Ford Motor Company from September 2006 to June 2014, while also serving on Ford’s board and its finance committee during that same period. Before Ford, from March 2001 to September 2006, he was Executive Vice President of The Boeing Company and President and CEO of Boeing Commercial Airplanes, and he sat on the Boeing Executive Council. Earlier, he served as President of Boeing’s space and defense business. Beyond those roles, he was co-chair of the Washington Competitiveness Council and served on advisory boards for NASA, the University of Washington, the University of Kansas, MIT, and the U.S. Air Force Scientific Advisory Board.",
    "John announced he will resign as President of Stanford University in August 2016. Ann Mather has been on our Board since November 2005 and currently serves on the boards of Arista Networks (since June 2013, audit committee chair), Glu Mobile (since September 2005, nominating and corporate governance committee), Netflix (since July 2010, audit committee chair), and Shutterfly (since May 2013, audit committee). She has been an independent trustee of the Dodge & Cox Funds since May 2011. Previously, she was a director of MoneyGram International (May 2010–May 2013) and Solazyme (April 2011–November 2014). Her executive roles include EVP & CFO at Pixar (1999–2004) and earlier EVP & CFO at Village Roadshow Pictures. She holds an M.A. from Cambridge University and is a chartered accountant. Alan R. Mulally has served on our Board since July 2014.",
    "Mostly leased warehouses and sales offices; about 80% owned for testing/prototype/operations space. Outside the U.S., Ford owns most plants and engineering centers, while many parts distribution centers are leased or vendor-provided. Overall it uses 375+ facilities in 24 countries, including 41 manufacturing/assembly plants supporting Ford Blue, Model e, and Ford Pro. Ford’s lone consolidated manufacturing JV is Ford Vietnam Limited (Ford 75% / VEAM affiliate 25%), which assembles and distributes Ford vehicles",
    "Level 2 uses observable inputs (e.g., agency and municipal securities, corporates, MBS/ABS, foreign gov bonds; plus cleared and OTC derivatives) priced with market data. Level 3 relies on unobservable inputs and models (DCF, option pricing) for items like certain corporates/munis and impaired goodwill/intangibles. Equity investments without readily determinable fair values are measured nonrecurringly using the best available techniques (market quotes/comparables or DCF). Other current financial assets/liabilities approximate carrying value. Property and equipment is at cost, depreciated straight-line over the shorter of useful life or lease term.",
    "Higher rates and energy costs, inflation/deflation, weak housing, unemployment, lower GDP/disposable income, tight credit, FX swings, tax and healthcare law changes, tariffs/trade barriers, or recession can curb demand, push mix to lower-margin items, slow inventory turns and force markdowns. They also lift COGS and SG&A (transport, labor, insurance, healthcare, commodities), risk impairments, strain suppliers (higher costs or reduced output), and cause partnerships/alliances to underperform.",
    "In 2024 Pfizer booked $945M gains from partial Haleon sales, $272M dividends from ViiV, and a $420M charge tied to an expected facility sale from discontinuing the DMD program. It recorded $3.295B of intangible impairments (all Level 3 fair value): IPR&D $1.873B, developed tech rights $943M, finite-lived brand $475M, and licensing $5M; fair value was measured via the income approach (multi-period excess earnings/DCF). (FYI context: 2023 included ViiV $265M, Nimbus $211M dividends and a $222M gain on an early-stage gene therapy divestiture to Alexion; 2022 included ViiV $314M, TSAs net $142M, and $77M contingent-consideration charges.",
    "Ford filed a Form 10-K for the year ended Dec 31, 2024 (Commission File 1-3950). It’s a Delaware registrant (EIN 38-0549190) headquartered at One American Road, Dearborn, MI 48126 (313-322-3000). Ford is a well-known seasoned issuer and a large accelerated filer (not smaller or emerging growth). Listed on the NYSE: Common Stock (ticker F) and senior notes FPRB, FPRC, FPRD."

]

In [90]:

assert len(ground_truth) == len(df_preds), "ground_truth length must match df_preds"


df_preds["ground_truth"] = ground_truth


df_preds["ground_truths"] = [
    [gt] if gt is not None and gt != "" else []
    for gt in ground_truth
]

df_preds.head()

,question,prediction,ground_truth,ground_truths
0,What major risks does Alphabet cite from operating internationally and from financial exposures?,Alphabet Inc.,"Alphabet flags anti-bribery compliance (the FCPA and comparable local laws), cross-country labor and HR differences that add operational complexity, and foreign-currency risk t...","[Alphabet flags anti-bribery compliance (the FCPA and comparable local laws), cross-country labor and HR differences that add operational complexity, and foreign-currency risk ..."
1,"Summarize Alan R. Mulally’s service on the company’s board and his prior leadership at Ford and Boeing, including dates, committee memberships, and key advisory roles.","[aIG_10K.pdf pp.107–107]\nFORD MOTOR COMPANY BY: /s/ Mark Kosman Mark Kosman, Chief Accounting Officer (principal accounting officer) Date: February 5, 2025 Pursuant to the req...","Alan R. Mulally has served on the company’s Board of Directors since July 2014. He was President and CEO of Ford Motor Company from September 2006 to June 2014, while also serv...","[Alan R. Mulally has served on the company’s Board of Directors since July 2014. He was President and CEO of Ford Motor Company from September 2006 to June 2014, while also ser..."
2,"Summarize the key governance and career details mentioned: John’s planned resignation from Stanford, Ann Mather’s current board seats and committee roles, her prior directorshi...","John has served as the President of Stanford University since September 2000, and he has also served as a member of the Board of Directors of Cisco Systems, Inc. and as the Cha...",John announced he will resign as President of Stanford University in August 2016. Ann Mather has been on our Board since November 2005 and currently serves on the boards of Ari...,[John announced he will resign as President of Stanford University in August 2016. Ann Mather has been on our Board since November 2005 and currently serves on the boards of Ar...
3,"In brief, what does Ford’s global facilities footprint and ownership/lease mix look like as of Dec 31, 2024?",[ERROR] CUDA out of memory. Tried to allocate 618.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 52.12 MiB is free. Process 167004 has 14.69 GiB memory in use. Of the...,"Mostly leased warehouses and sales offices; about 80% owned for testing/prototype/operations space. Outside the U.S., Ford owns most plants and engineering centers, while many ...","[Mostly leased warehouses and sales offices; about 80% owned for testing/prototype/operations space. Outside the U.S., Ford owns most plants and engineering centers, while many..."
4,"Briefly explain how Microsoft measures fair value for Level 2 and Level 3 items, how it values equity investments without readily determinable fair values, and its policy for p...","Microsoft uses the market approach, which includes three levels of inputs and liabilities in active markets, and observable inputs for the asset or liability.","Level 2 uses observable inputs (e.g., agency and municipal securities, corporates, MBS/ABS, foreign gov bonds; plus cleared and OTC derivatives) priced with market data. Level ...","[Level 2 uses observable inputs (e.g., agency and municipal securities, corporates, MBS/ABS, foreign gov bonds; plus cleared and OTC derivatives) priced with market data. Level..."

In [91]:
df_ragas = df_preds.copy()
df_ragas = df_ragas.rename(columns={"prediction": "answer"})

In [92]:
def get_contexts(q, k=5):
    hits = retrieve_with_citations(q, k=k)
    return [h["text"] for h in hits]

df_ragas["contexts"] = df_ragas["question"].apply(lambda q: get_contexts(q, k=5))

df_ragas = df_ragas[["question", "answer", "contexts", "ground_truths"]]

df_ragas.head()

,question,answer,contexts,ground_truths
0,What major risks does Alphabet cite from operating internationally and from financial exposures?,Alphabet Inc.,"[In addition, our products and services are highly technical and complex and have contained in the past, and may contain in the future, errors or vulnerabilities, which could r...","[Alphabet flags anti-bribery compliance (the FCPA and comparable local laws), cross-country labor and HR differences that add operational complexity, and foreign-currency risk ..."
1,"Summarize Alan R. Mulally’s service on the company’s board and his prior leadership at Ford and Boeing, including dates, committee memberships, and key advisory roles.","[aIG_10K.pdf pp.107–107]\nFORD MOTOR COMPANY BY: /s/ Mark Kosman Mark Kosman, Chief Accounting Officer (principal accounting officer) Date: February 5, 2025 Pursuant to the req...","[Alan R. Mulally has served as a member of our Board of Directors since July 2014. Alan served as President and Chief Executive Officer of Ford Motor Company, a global automoti...","[Alan R. Mulally has served on the company’s Board of Directors since July 2014. He was President and CEO of Ford Motor Company from September 2006 to June 2014, while also ser..."
2,"Summarize the key governance and career details mentioned: John’s planned resignation from Stanford, Ann Mather’s current board seats and committee roles, her prior directorshi...","John has served as the President of Stanford University since September 2000, and he has also served as a member of the Board of Directors of Cisco Systems, Inc. and as the Cha...",[John has announced that he plans to resign from his position as the President of Stanford University in August 2016. Ann Mather has served as a member of our Board of Director...,[John announced he will resign as President of Stanford University in August 2016. Ann Mather has been on our Board since November 2005 and currently serves on the boards of Ar...
3,"In brief, what does Ford’s global facilities footprint and ownership/lease mix look like as of Dec 31, 2024?",[ERROR] CUDA out of memory. Tried to allocate 618.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 52.12 MiB is free. Process 167004 has 14.69 GiB memory in use. Of the...,"[The majority of the warehouses that we operate are leased, although many of our manufacturing and assembly facilities contain some warehousing space. Substantially all of our ...","[Mostly leased warehouses and sales offices; about 80% owned for testing/prototype/operations space. Outside the U.S., Ford owns most plants and engineering centers, while many..."
4,"Briefly explain how Microsoft measures fair value for Level 2 and Level 3 items, how it values equity investments without readily determinable fair values, and its policy for p...","Microsoft uses the market approach, which includes three levels of inputs and liabilities in active markets, and observable inputs for the asset or liability.","[Fair value is defined as the exit price, or the amount that would be received to sell an asset or paid to transfer a liability in an orderly transaction between market partici...","[Level 2 uses observable inputs (e.g., agency and municipal securities, corporates, MBS/ABS, foreign gov bonds; plus cleared and OTC derivatives) priced with market data. Level..."

Loaded 8 rows; examples of contexts lens: [5, 5, 5, 5, 5]

In [6]:
## Due to complex implimentaion i have referenced this ccode from ChatGPT

import os, re, math, numpy as np, pandas as pd
from typing import List, Dict
from sentence_transformers import SentenceTransformer
from openai import OpenAI


os.environ["OPENAI_API_KEY"] = "xxxxxxxxxxxxxxxxxxx"
JUDGE_MODEL = "gpt-4o"
EMBED_MODEL = "sentence-transformers/all-mpnet-base-v2"
TOP_K_SENTENCES = 6
SIM_THRESHOLD = 0.35


client = OpenAI()
embedder = SentenceTransformer(EMBED_MODEL)
embedder.max_seq_length = 384

def _norm_text(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip())

def _sentences(text: str) -> List[str]:

    parts = re.split(r"(?<=[.!?])\s+", text or "")
    return [p.strip() for p in parts if p.strip()]

def _embed(texts: List[str]) -> np.ndarray:
    vecs = embedder.encode(texts, normalize_embeddings=True, convert_to_numpy=True, show_progress_bar=False)
    return vecs

def _cos(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b))

def judge_yes_no(prompt: str) -> float:
    """
    Calls the judge LLM. Returns 1.0 for 'yes', 0.0 for 'no' (or in-between if model outputs a probability).
    We map 'yes'->1, 'no'->0, else try to parse a numeric score.
    """
    msg = [{"role": "user", "content": prompt}]
    out = client.chat.completions.create(model=JUDGE_MODEL, messages=msg, temperature=0)
    text = out.choices[0].message.content.strip().lower()

    m = re.search(r"(\b0(\.\d+)?|\b1(\.0+)?|\b0\.\d+|\b\d{1,2}%|\b100%)", text)
    if m:
        s = m.group(0)
        if s.endswith("%"):
            return min(1.0, max(0.0, float(s[:-1]) / 100.0))
        try:
            return min(1.0, max(0.0, float(s)))
        except:
            pass
    if "yes" in text and "no" not in text:
        return 1.0
    if "no" in text and "yes" not in text:
        return 0.0

    return 0.5


def answer_relevancy_score(question: str, answer: str) -> float:
    """
    relavancy of the answers
    """
    prompt = f"""
You are grading answer relevance. Score between 0 and 1 where:
0 = off-topic, 1 = fully answers the question.

Question:
{question}

Answer:
{answer}

Return only a number between 0 and 1 (or a percentage).
"""
    return judge_yes_no(prompt)

def faithfulness_score(answer: str, contexts: List[str]) -> float:
    """
    faithufullness score
    """
    ctx = "\n\n".join(contexts)
    prompt = f"""
You are grading faithfulness to context. Score between 0 and 1 where:
1 = every factual claim in the answer is supported by the CONTEXT, 0 = unsupported/hallucinated.

CONTEXT:
{ctx}

ANSWER:
{answer}

Return only a number between 0 and 1 (or a percentage).
"""
    return judge_yes_no(prompt)

def context_precision_score(question: str, contexts: List[str]) -> float:

    qv = _embed([question])[0]
    sent_list = []
    for c in contexts:
        sents = _sentences(c)[:TOP_K_SENTENCES]
        sent_list.extend(sents)
    if not sent_list:
        return 0.0
    sv = _embed(sent_list)
    sims = sv @ qv
    relevant = (sims >= SIM_THRESHOLD).sum()
    return float(relevant) / len(sent_list)

def context_recall_score(question: str, contexts: List[str], ground_truths: List[str]) -> float:

    gts = [g for g in ground_truths if g and g.strip()]
    if not gts:
        return 0.0

    sent_list = []
    for c in contexts:
        sent_list.extend(_sentences(c)[:TOP_K_SENTENCES])
    if not sent_list:
        return 0.0
    sent_vecs = _embed(sent_list)
    covered = 0
    for gt in gts:
        gt_vec = _embed([gt])[0]
        sims = sent_vecs @ gt_vec
        if float(np.max(sims)) >= SIM_THRESHOLD:
            covered += 1
    return covered / len(gts)


def evaluate_rag(df: pd.DataFrame) -> pd.DataFrame:
    """
    This will evaluate both predictiona and ground truth
    """
    rows = []
    for i, r in df.iterrows():
        q = _norm_text(r["question"])
        a = _norm_text(r["answer"])
        ctxs = list(r["contexts"])
        gts  = list(r["ground_truths"])

        ar  = answer_relevancy_score(q, a)
        fa  = faithfulness_score(a, ctxs)
        cp  = context_precision_score(q, ctxs)
        cr  = context_recall_score(q, ctxs, gts)

        rows.append({
            "question": q,
            "answer": a,
            "answer_relevancy": ar,
            "faithfulness": fa,
            "context_precision": cp,
            "context_recall": cr,
        })
    return pd.DataFrame(rows)


scores_df = evaluate_rag(df_ragas)
pd.set_option("display.max_colwidth", 180)
display(scores_df.head())

# Aggregate means
agg = scores_df[["answer_relevancy","faithfulness","context_precision","context_recall"]].mean().to_dict()
print("\n== Aggregate (mean) ==")
for k, v in agg.items():
    print(f"{k}: {v:.3f}")

,question,answer,answer_relevancy,faithfulness,context_precision,context_recall
0,What major risks does Alphabet cite from operating internationally and from financial exposures?,Alphabet Inc.,0.0,0.00,0.566667,1.0
1,"Summarize Alan R. Mulally’s service on the company’s board and his prior leadership at Ford and Boeing, including dates, committee memberships, and key advisory roles.","[aIG_10K.pdf pp.107–107] FORD MOTOR COMPANY BY: /s/ Mark Kosman Mark Kosman, Chief Accounting Officer (principal accounting officer) Date: February 5, 2025 Pursuant to the requ...",0.0,0.00,0.600000,1.0
2,"Summarize the key governance and career details mentioned: John’s planned resignation from Stanford, Ann Mather’s current board seats and committee roles, her prior directorshi...","John has served as the President of Stanford University since September 2000, and he has also served as a member of the Board of Directors of Cisco Systems, Inc. and as the Cha...",0.0,0.75,0.666667,1.0
3,"In brief, what does Ford’s global facilities footprint and ownership/lease mix look like as of Dec 31, 2024?",[ERROR] CUDA out of memory. Tried to allocate 618.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 52.12 MiB is free. Process 167004 has 14.69 GiB memory in use. Of the...,0.0,0.00,0.633333,1.0
4,"Briefly explain how Microsoft measures fair value for Level 2 and Level 3 items, how it values equity investments without readily determinable fair values, and its policy for p...","Microsoft uses the market approach, which includes three levels of inputs and liabilities in active markets, and observable inputs for the asset or liability.",0.5,0.00,0.766667,1.0

== Aggregate (mean) ==
answer_relevancy: 0.062
faithfulness: 0.094
context_precision: 0.633
context_recall: 1.000